use std::collections::BTreeSet;
use std::path::Path;

use crate::types::{CppAst, CppClass, CppEnum, CppFunction};

pub fn generate_entrypoint(asts: &[CppAst]) -> String {
    let mut out = String::new();
    let includes = collect_includes(asts);

    out.push_str("hicc::cpp! {\n");
    if includes.is_empty() {
        out.push_str("}\n\n");
    } else {
        for include in includes {
            out.push_str(&format!("    #include \"{include}\"\n"));
        }
        out.push_str("}\n\n");
    }

    out.push_str(&generate_class_imports(asts));
    out.push('\n');
    out.push_str(&generate_library_imports(asts));
    out.push('\n');
    out.push_str("fn main() {\n");
    out.push_str("    println!(\"Generated by cpp2rust-ffi\");\n");
    out.push_str("}\n");

    out
}

fn collect_includes(asts: &[CppAst]) -> BTreeSet<String> {
    asts.iter()
        .filter_map(|ast| {
            Path::new(&ast.source_file)
                .file_stem()
                .and_then(|stem| stem.to_str())
                .map(|stem| format!("{stem}.h"))
        })
        .collect()
}

fn generate_class_imports(asts: &[CppAst]) -> String {
    let mut out = String::from("hicc::import_class! {\n");
    for class in asts.iter().flat_map(|ast| ast.classes.iter()) {
        emit_class(&mut out, class);
    }
    out.push_str("}\n");
    out
}

fn emit_class(out: &mut String, class: &CppClass) {
    out.push_str(&format!(
        "    #[cpp(class = \"{}\")]\n",
        qualified_name(&class.namespace, &class.name)
    ));
    out.push_str(&format!("    class {} {{\n", class.name));
    for method in &class.methods {
        let params = method
            .params
            .iter()
            .map(|param| {
                format!(
                    "{}: {}",
                    sanitize_ident(&param.name),
                    param.type_.to_rust_ffi()
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        let receiver = if method.is_static {
            String::new()
        } else if method.is_const {
            "&self".to_string()
        } else {
            "&mut self".to_string()
        };
        let signature = if receiver.is_empty() {
            params.clone()
        } else if params.is_empty() {
            receiver.clone()
        } else {
            format!("{receiver}, {params}")
        };
        out.push_str(&format!(
            "        #[cpp(method = \"{}\")]\n        fn {}({}) -> {};\n",
            method.name,
            sanitize_ident(&method.name),
            signature,
            method.return_type.to_rust_ffi()
        ));
    }
    out.push_str("    }\n");
}

fn generate_library_imports(asts: &[CppAst]) -> String {
    let mut out =
        String::from("hicc::import_lib! {\n    #![link_name = \"cpp2rust_generated\"]\n\n");
    for class in asts.iter().flat_map(|ast| ast.classes.iter()) {
        out.push_str(&format!("    class {};\n", class.name));
    }
    if !asts.iter().all(|ast| ast.classes.is_empty()) {
        out.push('\n');
    }
    for function in asts.iter().flat_map(|ast| ast.functions.iter()) {
        emit_function(&mut out, function);
    }
    for cpp_enum in asts.iter().flat_map(|ast| ast.enums.iter()) {
        emit_enum_comment(&mut out, cpp_enum);
    }
    out.push_str("}\n");
    out
}

fn emit_function(out: &mut String, function: &CppFunction) {
    let params = function
        .params
        .iter()
        .map(|param| {
            format!(
                "{}: {}",
                sanitize_ident(&param.name),
                param.type_.to_rust_ffi()
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let cpp_sig = format!(
        "{} {}({})",
        function.return_type.name,
        qualified_name(&function.namespace, &function.name),
        function
            .params
            .iter()
            .map(|param| format!("{} {}", param.type_.name, param.name))
            .collect::<Vec<_>>()
            .join(", ")
    );
    out.push_str(&format!("    #[cpp(func = \"{}\")]\n", cpp_sig.trim()));
    out.push_str(&format!(
        "    fn {}({}) -> {};\n\n",
        sanitize_ident(&function.name),
        params,
        function.return_type.to_rust_ffi()
    ));
}

fn emit_enum_comment(out: &mut String, cpp_enum: &CppEnum) {
    out.push_str(&format!(
        "    // enum {} with {} variants\n",
        qualified_name(&cpp_enum.namespace, &cpp_enum.name),
        cpp_enum.variants.len()
    ));
}

fn qualified_name(namespace: &[String], name: &str) -> String {
    if namespace.is_empty() {
        name.to_string()
    } else {
        format!("{}::{}", namespace.join("::"), name)
    }
}

fn sanitize_ident(name: &str) -> String {
    let sanitized = name
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>();
    match sanitized.as_str() {
        "self" => "self_".to_string(),
        "" => "unnamed".to_string(),
        other => other.to_string(),
    }
}
