//! Code generation: turn `ExtractedDecls` into hicc FFI Rust source code.
//!
//! The output consists of:
//!
//! 1. **`hicc::import_class!` blocks** – one per C++ class, mapping public
//!    methods to Rust fn signatures with `#[cpp(method = "...")]`.
//! 2. **`hicc::import_lib!` block** – a single block containing:
//!    - `class Foo;` forward declarations for every referenced class, and
//!    - `#[cpp(func = "...")]` fn items for all free functions (and static
//!      methods, which hicc exposes as free functions).
//! 3. A stub **`build.rs`** for the generated crate that uses `hicc-build` to
//!    compile the C++ adapter code.
//! 4. A minimal **`Cargo.toml`** for the generated crate.

use crate::ast::{ClassIR, ExtractedDecls, FunctionIR, SkippedDecl};
use std::fmt::Write as _;

// ---------------------------------------------------------------------------
// Public entry-point
// ---------------------------------------------------------------------------

/// Render the full `ffi.rs` content for a feature.
///
/// `source_file_path` is the absolute path to the selected middleware file.
/// The generated file includes a `hicc::cpp!` block that `#include`s only the
/// basename, so its parent directory must be added to the compiler include path via
/// `build.rs` (see [`render_build_rs`]).
#[allow(dead_code)]
pub fn render_ffi(decls: &ExtractedDecls, link_name: &str, source_file_path: &str) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by cpp2rust-demo.").unwrap();
    writeln!(out, "// Source file : {}", source_file_path).unwrap();
    writeln!(out, "// Link library   : {}", link_name).unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// DO NOT EDIT — run `cpp2rust-demo merge` to consolidate."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#![allow(non_snake_case, dead_code)]").unwrap();
    writeln!(out).unwrap();

    out.push_str(&render_include_module(source_file_path));
    let class_part = render_class_module(decls);
    if !class_part.is_empty() {
        out.push_str(&class_part);
        out.push('\n');
    }
    out.push_str(&render_free_module(decls, link_name));

    out
}

pub fn render_include_module(source_file_path: &str) -> String {
    let mut out = String::new();
    let include_basename = std::path::Path::new(source_file_path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or(source_file_path);
    writeln!(out, "hicc::cpp! {{").unwrap();
    writeln!(out, "    #include \"{}\"", include_basename).unwrap();
    writeln!(out, "}}").unwrap();
    out
}

pub fn render_class_module(decls: &ExtractedDecls) -> String {
    let mut out = String::new();
    if decls.classes.is_empty() {
        return out;
    }
    writeln!(out, "// Class-level metadata for this middleware group.").unwrap();
    writeln!(
        out,
        "pub const CLASS_COUNT: usize = {};",
        decls.classes.len()
    )
    .unwrap();
    let method_counts: Vec<usize> = decls.classes.iter().map(|c| c.methods.len()).collect();
    let static_method_counts: Vec<usize> = decls
        .classes
        .iter()
        .map(|c| c.methods.iter().filter(|m| m.is_static).count())
        .collect();
    let mut class_methods: Vec<(&str, &str)> = Vec::new();
    let mut class_instance_methods: Vec<(&str, &str)> = Vec::new();
    for class in &decls.classes {
        for method in &class.methods {
            class_methods.push((
                class.qualified_name.as_str(),
                method.qualified_name.as_str(),
            ));
            if !method.is_static {
                class_instance_methods.push((
                    class.qualified_name.as_str(),
                    method.qualified_name.as_str(),
                ));
            }
        }
    }
    out.push_str(&render_string_slice(
        "CLASS_NAMES",
        &decls
            .classes
            .iter()
            .map(|c| c.qualified_name.as_str())
            .collect::<Vec<_>>(),
    ));
    out.push_str(&render_usize_slice("CLASS_METHOD_COUNTS", &method_counts));
    out.push_str(&render_usize_slice(
        "CLASS_STATIC_METHOD_COUNTS",
        &static_method_counts,
    ));
    out.push_str(&render_pair_slice("CLASS_METHODS", &class_methods));
    out.push_str(&render_pair_slice(
        "CLASS_INSTANCE_METHODS",
        &class_instance_methods,
    ));
    out.push_str(
        "\
pub fn class_method_count(class_name: &str) -> Option<usize> {\n\
    CLASS_NAMES\n\
        .iter()\n\
        .position(|name| *name == class_name)\n\
        .map(|idx| CLASS_METHOD_COUNTS[idx])\n\
}\n\
\n\
pub fn class_static_method_count(class_name: &str) -> Option<usize> {\n\
    CLASS_NAMES\n\
        .iter()\n\
        .position(|name| *name == class_name)\n\
        .map(|idx| CLASS_STATIC_METHOD_COUNTS[idx])\n\
}\n\
\n\
pub fn class_methods(class_name: &str) -> Vec<&'static str> {\n\
    CLASS_METHODS\n\
        .iter()\n\
        .filter_map(|(cls, method)| (*cls == class_name).then_some(*method))\n\
        .collect()\n\
}\n\
\n\
pub fn class_instance_methods(class_name: &str) -> Vec<&'static str> {\n\
    CLASS_INSTANCE_METHODS\n\
        .iter()\n\
        .filter_map(|(cls, method)| (*cls == class_name).then_some(*method))\n\
        .collect()\n\
}\n",
    );
    out
}

pub fn render_method_module(decls: &ExtractedDecls) -> String {
    let mut out = String::new();
    for class in &decls.classes {
        render_import_class(&mut out, class);
        writeln!(out).unwrap();
    }
    out
}

pub fn render_free_module(decls: &ExtractedDecls, link_name: &str) -> String {
    let mut out = String::new();
    render_import_lib(&mut out, decls, link_name);
    out
}

pub fn render_types_module(decls: &ExtractedDecls) -> String {
    let mut cpp_types = std::collections::BTreeSet::new();
    let mut cpp_rust_type_mappings = std::collections::BTreeMap::new();
    for f in &decls.functions {
        cpp_types.insert(f.return_type.as_str());
        cpp_rust_type_mappings
            .entry(f.return_type.as_str())
            .or_insert(f.rust_return_type.as_str());
        for p in &f.params {
            cpp_types.insert(p.cpp_type.as_str());
            cpp_rust_type_mappings
                .entry(p.cpp_type.as_str())
                .or_insert(p.rust_type.as_str());
        }
    }
    for c in &decls.classes {
        for m in &c.methods {
            cpp_types.insert(m.return_type.as_str());
            cpp_rust_type_mappings
                .entry(m.return_type.as_str())
                .or_insert(m.rust_return_type.as_str());
            for p in &m.params {
                cpp_types.insert(p.cpp_type.as_str());
                cpp_rust_type_mappings
                    .entry(p.cpp_type.as_str())
                    .or_insert(p.rust_type.as_str());
            }
        }
    }
    let values: Vec<&str> = cpp_types.into_iter().collect();
    let mappings: Vec<(&str, &str)> = cpp_rust_type_mappings
        .into_iter()
        .collect::<Vec<(&str, &str)>>();
    let mut out = String::from("// Per-group C++ type inventory extracted from AST.\n");
    out.push_str(&format!(
        "pub const CPP_TYPE_COUNT: usize = {};\n",
        values.len()
    ));
    out.push_str(&render_string_slice("CPP_TYPES", &values));
    out.push_str(&render_pair_slice("CPP_RUST_TYPE_MAPPINGS", &mappings));
    out.push_str(
        "\
pub fn rust_type_for(cpp_type: &str) -> Option<&'static str> {\n\
    CPP_RUST_TYPE_MAPPINGS\n\
        .iter()\n\
        .find_map(|(cpp, rust)| (*cpp == cpp_type).then_some(*rust))\n\
}\n\
\n\
pub fn has_cpp_type(cpp_type: &str) -> bool {\n\
    CPP_TYPES.iter().any(|ty| *ty == cpp_type)\n\
}\n",
    );
    out
}

/// Render a standalone `Cargo.toml` for the generated Rust crate.
pub fn render_cargo_toml(crate_name: &str, link_name: &str) -> String {
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
hicc = "0.2.3"

[build-dependencies]
hicc-build = "0.2.1"

# The C++ shared/static library to link against.
# Adjust the search path with [package.metadata] or a custom build.rs.
[package.metadata.cpp2rust]
link_name = "{link_name}"
"#
    )
}

/// Render a `build.rs` for the generated Rust crate.
///
/// * `rust_files` – paths to the `.rs` files that contain hicc macros.
/// * `include_dirs` – directories to add as C++ compiler include paths so
///   that `hicc::cpp!` can find the included middleware file.
pub fn render_build_rs(
    link_name: &str,
    no_link: bool,
    rust_files: &[&str],
    include_dirs: &[&str],
) -> String {
    let file_calls: String = rust_files
        .iter()
        .map(|f| format!("    build.rust_file(\"{}\");\n", f))
        .collect();
    let include_calls: String = include_dirs
        .iter()
        .map(|d| format!("    build.include(\"{}\");\n", d))
        .collect();
    // Build the portability note only when include dirs are present.
    let portability_note = if include_dirs.is_empty() {
        String::new()
    } else {
        String::from(
            "    // NOTE: The include paths above are absolute paths recorded at init time.\n\
             //       If you copy this project to another machine, update them to point\n\
             //       to the captured middleware files on the new machine (or use relative paths).\n",
        )
    };
    let external_link_call = if no_link {
        "    // Header-only / no-link mode: skip linking external C++ target library.\n".to_string()
    } else {
        format!(
            "    // Link the actual C++ library (adjust the search path as needed).\n    println!(\"cargo::rustc-link-lib={link_name}\");\n"
        )
    };
    format!(
        r#"fn main() {{
    let mut build = hicc_build::Build::new();
{file_calls}{include_calls}{portability_note}    build.compile("cpp2rust_adapter");
    println!("cargo::rustc-link-lib=cpp2rust_adapter");
    println!("cargo::rustc-link-lib=stdc++");
{external_link_call}
}}
"#
    )
}

/// Render the top-level `lib.rs` that re-exports the given FFI modules.
pub fn render_lib_rs(modules: &[&str]) -> String {
    let mut out = String::from("// Auto-generated by cpp2rust-demo.\n");
    for module in modules {
        out.push_str(&format!("pub mod {};\n", module));
        out.push_str(&format!("pub use {}::*;\n", module));
    }
    out
}

// ---------------------------------------------------------------------------
// Internal rendering helpers
// ---------------------------------------------------------------------------

fn render_import_class(out: &mut String, class: &ClassIR) {
    // Only include instance methods (non-static) in import_class!
    let instance_methods: Vec<&FunctionIR> =
        class.methods.iter().filter(|m| !m.is_static).collect();

    if instance_methods.is_empty() {
        // Don't emit an empty import_class! block; the class will still be
        // forward-declared in import_lib! (if it is not abstract).
        return;
    }

    writeln!(out, "hicc::import_class! {{").unwrap();
    if class.is_abstract {
        // Fully-abstract C++ class: map to a hicc `#[interface]` trait.
        // hicc uses #[interface] instead of #[cpp(class = "...")] for pure-virtual
        // interfaces; the generated Rust trait can then be used as a bound.
        writeln!(out, "    #[interface]").unwrap();
        writeln!(out, "    class {} {{", class.name).unwrap();
    } else {
        writeln!(out, "    #[cpp(class = \"{}\")]", class.qualified_name).unwrap();
        writeln!(out, "    class {} {{", class.name).unwrap();
    }

    for method in &instance_methods {
        render_method(out, method);
    }

    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

fn render_string_slice(name: &str, values: &[&str]) -> String {
    let mut out = String::new();
    writeln!(out, "pub const {}: &[&str] = &[", name).unwrap();
    for value in values {
        writeln!(out, "    {:?},", value).unwrap();
    }
    writeln!(out, "];").unwrap();
    out
}

fn render_usize_slice(name: &str, values: &[usize]) -> String {
    let mut out = String::new();
    writeln!(out, "pub const {}: &[usize] = &[", name).unwrap();
    for value in values {
        writeln!(out, "    {},", value).unwrap();
    }
    writeln!(out, "];").unwrap();
    out
}

fn render_pair_slice(name: &str, values: &[(&str, &str)]) -> String {
    let mut out = String::new();
    writeln!(out, "pub const {}: &[(&str, &str)] = &[", name).unwrap();
    for (left, right) in values {
        writeln!(out, "    ({:?}, {:?}),", left, right).unwrap();
    }
    writeln!(out, "];").unwrap();
    out
}

fn render_method(out: &mut String, func: &FunctionIR) {
    // Build the method signature for #[cpp(method = "...")]
    // The signature is relative to the class, so we use the bare method
    // signature without the class name prefix.
    let param_types: Vec<&str> = func.params.iter().map(|p| p.cpp_type.as_str()).collect();
    let const_suffix = if func.is_const { " const" } else { "" };
    let method_sig = format!(
        "{} {}({}){}",
        func.return_type,
        func.name,
        param_types.join(", "),
        const_suffix
    );

    writeln!(out, "        #[cpp(method = \"{method_sig}\")]").unwrap();

    // Build the Rust method signature.
    let self_arg = if func.is_static {
        // Static methods don't take self.
        String::new()
    } else if func.is_const {
        "&self, ".to_string()
    } else {
        "&mut self, ".to_string()
    };

    let rust_params = render_rust_params(&func.params, &self_arg);
    let ret = render_return_type(&func.rust_return_type);

    writeln!(out, "        fn {}{}{};", func.rust_name, rust_params, ret).unwrap();
}

fn render_import_lib(out: &mut String, decls: &ExtractedDecls, link_name: &str) {
    writeln!(out, "hicc::import_lib! {{").unwrap();
    writeln!(out, "    #![link_name = \"{link_name}\"]").unwrap();
    writeln!(out).unwrap();

    // Forward-declare every concrete class used so hicc knows they are C++ types.
    // Abstract classes (mapped to #[interface] traits) are not forward-declared
    // here: they are not concrete value types in hicc.
    for class in &decls.classes {
        if !class.is_abstract {
            writeln!(out, "    class {};", class.name).unwrap();
        }
    }

    // Collect all static methods as free functions.
    let static_methods: Vec<&FunctionIR> = decls
        .classes
        .iter()
        .flat_map(|c| c.methods.iter())
        .filter(|m| m.is_static)
        .collect();

    let has_content = !decls.functions.is_empty() || !static_methods.is_empty();
    if has_content && !decls.classes.is_empty() {
        writeln!(out).unwrap();
    }

    // Free functions.
    for func in &decls.functions {
        render_free_function(out, func);
        writeln!(out).unwrap();
    }

    // Static class methods exposed as free functions.
    for func in static_methods {
        // Use class_name::rust_name as the Rust fn name.
        let prefixed = if let Some(ref cls) = func.class_name {
            format!("{}_{}", crate::ast::to_snake_case(cls), func.rust_name)
        } else {
            func.rust_name.clone()
        };
        render_free_function_with_name(out, func, &prefixed);
        writeln!(out).unwrap();
    }

    writeln!(out, "}}").unwrap();
}

fn render_free_function(out: &mut String, func: &FunctionIR) {
    render_free_function_with_name(out, func, &func.rust_name);
}

fn render_free_function_with_name(out: &mut String, func: &FunctionIR, rust_name: &str) {
    writeln!(out, "    #[cpp(func = \"{}\")]", func.cpp_signature).unwrap();
    let rust_params = render_rust_params(&func.params, "");
    let ret = render_return_type(&func.rust_return_type);
    writeln!(out, "    fn {}{}{};", rust_name, rust_params, ret).unwrap();
}

fn render_rust_params(params: &[crate::ast::ParamIR], self_prefix: &str) -> String {
    let param_strs: Vec<String> = params
        .iter()
        .map(|p| format!("{}: {}", sanitize_ident(&p.name), p.rust_type))
        .collect();

    let inner = if self_prefix.is_empty() {
        param_strs.join(", ")
    } else if param_strs.is_empty() {
        // Strip the trailing ", " from self_prefix (e.g. "&self, " → "&self").
        self_prefix.trim_end_matches(", ").to_string()
    } else {
        format!("{}{}", self_prefix, param_strs.join(", "))
    };
    format!("({})", inner)
}

fn render_return_type(rust_type: &str) -> String {
    if rust_type == "()" {
        String::new()
    } else {
        format!(" -> {}", rust_type)
    }
}

/// Ensure a parameter name is a valid Rust identifier (not a keyword).
fn sanitize_ident(name: &str) -> &str {
    match name {
        "type" | "impl" | "mod" | "use" | "pub" | "fn" | "let" | "mut" | "ref" | "move"
        | "loop" | "match" | "if" | "else" | "return" | "break" | "continue" | "where" | "for"
        | "while" | "in" | "as" | "crate" | "self" | "super" | "trait" | "struct" | "enum"
        | "union" | "extern" | "unsafe" | "async" | "await" | "dyn" | "box" | "abstract"
        | "become" | "final" | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield"
        | "do" | "try" | "macro" => "value",
        other => other,
    }
}

// ---------------------------------------------------------------------------
// Interface-checklist report
// ---------------------------------------------------------------------------

/// Generate a Markdown interface-checklist report, mirroring c2rust-demo's style.
pub fn render_interface_report(decls: &ExtractedDecls, link_name: &str, header: &str) -> String {
    let mut out = String::new();

    writeln!(out, "# FFI Interface Report").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "| Field | Value |").unwrap();
    writeln!(out, "|-------|-------|").unwrap();
    writeln!(out, "| Source file | `{}` |", header).unwrap();
    writeln!(out, "| Link name | `{}` |", link_name).unwrap();
    writeln!(out, "| Free functions | {} |", decls.functions.len()).unwrap();
    writeln!(out, "| Classes | {} |", decls.classes.len()).unwrap();
    writeln!(out, "| Skipped | {} |", decls.skipped.len()).unwrap();
    writeln!(out).unwrap();

    if !decls.functions.is_empty() {
        writeln!(out, "## Free Functions\n").unwrap();
        writeln!(out, "| C++ name | Rust name | Signature |").unwrap();
        writeln!(out, "|----------|-----------|-----------|").unwrap();
        for f in &decls.functions {
            writeln!(
                out,
                "| `{}` | `{}` | `{}` |",
                f.name, f.rust_name, f.cpp_signature
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    for class in &decls.classes {
        writeln!(out, "## Class `{}`\n", class.qualified_name).unwrap();
        writeln!(out, "| Method | Rust name | Const | Static |").unwrap();
        writeln!(out, "|--------|-----------|-------|--------|").unwrap();
        for m in &class.methods {
            writeln!(
                out,
                "| `{}` | `{}` | {} | {} |",
                m.name, m.rust_name, m.is_const, m.is_static
            )
            .unwrap();
        }
        writeln!(out).unwrap();
    }

    if !decls.skipped.is_empty() {
        writeln!(out, "## Skipped declarations\n").unwrap();
        writeln!(out, "| AST kind | Name | Reason |").unwrap();
        writeln!(out, "|----------|------|--------|").unwrap();
        for item in &decls.skipped {
            writeln!(
                out,
                "| `{}` | `{}` | `{}` |",
                item.kind, item.name, item.reason
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        // Dedicated section for operator overloads: guide users on how to
        // expose them manually via a hicc::cpp! wrapper.
        let operators: Vec<&SkippedDecl> = decls
            .skipped
            .iter()
            .filter(|s| s.reason == "operator_overload")
            .collect();
        if !operators.is_empty() {
            writeln!(out, "## Operator Overload Shim Hints\n").unwrap();
            writeln!(out, "The following C++ operators were skipped. hicc does not support\n\
                           operator overloads directly. Expose them by writing a named C++\n\
                           wrapper function inside a `hicc::cpp!` block and then binding\n\
                           that wrapper via `#[cpp(func = \"...\")]` in `import_lib!`.\n")
                .unwrap();
            writeln!(out, "| Skipped operator | Suggested approach |").unwrap();
            writeln!(out, "|-----------------|-------------------|").unwrap();
            for op in &operators {
                let suggestion = operator_shim_suggestion(&op.name);
                writeln!(out, "| `{}` | {} |", op.name, suggestion).unwrap();
            }
            writeln!(out).unwrap();
            writeln!(
                out,
                "**Example** – wrapping `operator[]` as a named function:\n\
                 \n\
                 ```rust\n\
                 hicc::cpp! {{\n\
                 //   static ReturnType get_at(MyClass& obj, IndexType idx) {{ return obj[idx]; }}\n\
                 }}\n\
                 hicc::import_lib! {{\n\
                 //   #![link_name = \"mylib\"]\n\
                 //   class MyClass;\n\
                 //   #[cpp(func = \"ReturnType get_at(MyClass&, IndexType)\")]\n\
                 //   fn get_at(obj: &mut MyClass, idx: IndexType) -> ReturnType;\n\
                 }}\n\
                 ```"
            )
            .unwrap();
            writeln!(out).unwrap();
        }
    }

    out
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Return a human-readable suggestion for how to shim a skipped operator overload.
fn operator_shim_suggestion(operator_name: &str) -> String {
    // Extract the operator token from the qualified name, e.g.
    // "rapidjson::Value::operator[]" → "operator[]"
    let op_token = operator_name
        .rsplit("::")
        .next()
        .unwrap_or(operator_name);
    match op_token {
        "operator[]" => "Wrap as `get_at(obj, idx)` / `set_at(obj, idx, val)`".to_string(),
        "operator=" => "Wrap as `assign(obj, other)` or use `AbiClass::write`".to_string(),
        "operator==" | "operator!=" | "operator<" | "operator<=" | "operator>" | "operator>=" => {
            format!("Wrap as a named comparison fn, e.g. `{}_eq(a, b)`", to_snake_case_op(op_token))
        }
        "operator+" | "operator-" | "operator*" | "operator/" => {
            format!("Wrap as a named arithmetic fn, e.g. `{}_add(a, b)`", to_snake_case_op(op_token))
        }
        "operator++" | "operator--" => {
            "Wrap as `increment(obj)` / `decrement(obj)`".to_string()
        }
        "operator()" => "Wrap as `call(obj, ...)` – expose as a named function".to_string(),
        "operator bool" | "operator int" | "operator double" => {
            "Wrap as a named conversion fn, e.g. `to_bool(obj)`".to_string()
        }
        _ => format!("Wrap `{}` as a named static function via `hicc::cpp!`", op_token),
    }
}

fn to_snake_case_op(op: &str) -> &str {
    match op {
        "operator==" => "eq",
        "operator!=" => "ne",
        "operator<" => "lt",
        "operator<=" => "le",
        "operator>" => "gt",
        "operator>=" => "ge",
        "operator+" => "add",
        "operator-" => "sub",
        "operator*" => "mul",
        "operator/" => "div",
        _ => "op",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ClassIR, ExtractedDecls, FunctionIR, ParamIR, SkippedDecl};

    fn make_fn(name: &str, rust_name: &str, ret: &str, params: Vec<ParamIR>) -> FunctionIR {
        let param_types: Vec<String> = params.iter().map(|p| p.cpp_type.clone()).collect();
        let cpp_sig = format!("{} {}({})", ret, name, param_types.join(", "));
        FunctionIR {
            name: name.to_string(),
            rust_name: rust_name.to_string(),
            return_type: ret.to_string(),
            rust_return_type: crate::ast::cpp_to_rust_type(ret),
            params,
            qualified_name: name.to_string(),
            cpp_signature: cpp_sig,
            is_const: false,
            is_static: false,
            is_virtual: false,
            is_pure: false,
            class_name: None,
        }
    }

    fn int_param(name: &str) -> ParamIR {
        ParamIR {
            name: name.to_string(),
            cpp_type: "int".to_string(),
            rust_type: "i32".to_string(),
        }
    }

    #[test]
    fn render_ffi_basic() {
        let decls = ExtractedDecls {
            functions: vec![make_fn(
                "add",
                "add",
                "int",
                vec![int_param("a"), int_param("b")],
            )],
            classes: vec![],
            skipped: vec![],
        };
        let src = render_ffi(&decls, "mylib", "mylib.hpp");
        assert!(src.contains("import_lib!"));
        assert!(src.contains(r#"link_name = "mylib""#));
        assert!(src.contains("fn add"));
        assert!(src.contains("a: i32"));
        assert!(src.contains("-> i32"));
    }

    #[test]
    fn render_ffi_void_return() {
        let decls = ExtractedDecls {
            functions: vec![make_fn("process", "process", "void", vec![int_param("v")])],
            classes: vec![],
            skipped: vec![],
        };
        let src = render_ffi(&decls, "mylib", "mylib.hpp");
        // void return should not produce `-> ()`.
        assert!(!src.contains("-> ()"));
        assert!(src.contains("fn process(v: i32)"));
    }

    #[test]
    fn render_cargo_toml_contains_hicc() {
        let toml = render_cargo_toml("my-ffi", "mylib");
        assert!(toml.contains("hicc"));
        assert!(toml.contains("hicc-build"));
        assert!(toml.contains("my-ffi"));
    }

    #[test]
    fn render_class_method() {
        let method = FunctionIR {
            name: "update".to_string(),
            rust_name: "update".to_string(),
            return_type: "void".to_string(),
            rust_return_type: "()".to_string(),
            params: vec![
                ParamIR {
                    name: "x".to_string(),
                    cpp_type: "double".to_string(),
                    rust_type: "f64".to_string(),
                },
                ParamIR {
                    name: "y".to_string(),
                    cpp_type: "double".to_string(),
                    rust_type: "f64".to_string(),
                },
            ],
            qualified_name: "Widget::update".to_string(),
            cpp_signature: "void Widget::update(double, double)".to_string(),
            is_const: false,
            is_static: false,
            is_virtual: false,
            is_pure: false,
            class_name: Some("Widget".to_string()),
        };
        let class = ClassIR {
            name: "Widget".to_string(),
            qualified_name: "Widget".to_string(),
            methods: vec![method],
            is_abstract: false,
        };
        let decls = ExtractedDecls {
            functions: vec![],
            classes: vec![class],
            skipped: vec![],
        };
        let method_src = render_method_module(&decls);
        assert!(method_src.contains("import_class!"));
        assert!(method_src.contains(r#"cpp(class = "Widget")"#));
        assert!(method_src.contains("fn update(&mut self, x: f64, y: f64)"));

        let class_src = render_class_module(&decls);
        assert!(class_src.contains("CLASS_COUNT"));
        assert!(class_src.contains("CLASS_NAMES"));
        assert!(class_src.contains("CLASS_METHOD_COUNTS"));
        assert!(class_src.contains("CLASS_STATIC_METHOD_COUNTS"));
        assert!(class_src.contains("CLASS_METHODS"));
        assert!(class_src.contains("CLASS_INSTANCE_METHODS"));
        assert!(class_src.contains("Widget::update"));
        assert!(class_src.contains("pub fn class_method_count"));
        assert!(class_src.contains("pub fn class_methods"));

        let free_src = render_free_module(&decls, "mywidget");
        assert!(free_src.contains("class Widget;"));

        let types_src = render_types_module(&decls);
        assert!(types_src.contains("CPP_RUST_TYPE_MAPPINGS"));
        assert!(types_src.contains("(\"double\", \"f64\")"));
        assert!(types_src.contains("(\"void\", \"()\")"));
        assert!(types_src.contains("pub fn rust_type_for"));
        assert!(types_src.contains("pub fn has_cpp_type"));
    }

    #[test]
    fn render_build_rs_no_link_skips_target_lib() {
        let src = render_build_rs("rapidjson", true, &["src/mod_a/include/mod.rs"], &[]);
        assert!(!src.contains("cargo::rustc-link-lib=rapidjson"));
        assert!(src.contains("cargo::rustc-link-lib=cpp2rust_adapter"));
    }

    #[test]
    fn render_interface_report_includes_skipped_reasons() {
        let decls = ExtractedDecls {
            functions: vec![],
            classes: vec![],
            skipped: vec![SkippedDecl {
                kind: "CXXMethodDecl".to_string(),
                name: "rapidjson::Value::operator[]".to_string(),
                reason: "operator_overload".to_string(),
            }],
        };
        let report = render_interface_report(&decls, "rapidjson", "rapid.cpp.cpp2rust");
        assert!(report.contains("## Skipped declarations"));
        assert!(report.contains("operator_overload"));
        // Operator shim hints section should appear.
        assert!(report.contains("## Operator Overload Shim Hints"));
        assert!(report.contains("get_at"));
        assert!(report.contains("hicc::cpp!"));
    }

    #[test]
    fn render_import_class_abstract_uses_interface_annotation() {
        let process = FunctionIR {
            name: "process".to_string(),
            rust_name: "process".to_string(),
            return_type: "int".to_string(),
            rust_return_type: "i32".to_string(),
            params: vec![int_param("x")],
            qualified_name: "IFoo::process".to_string(),
            cpp_signature: "int IFoo::process(int) const".to_string(),
            is_const: true,
            is_static: false,
            is_virtual: true,
            is_pure: true,
            class_name: Some("IFoo".to_string()),
        };
        let class = ClassIR {
            name: "IFoo".to_string(),
            qualified_name: "IFoo".to_string(),
            methods: vec![process],
            is_abstract: true,
        };
        let decls = ExtractedDecls {
            functions: vec![],
            classes: vec![class],
            skipped: vec![],
        };

        let method_src = render_method_module(&decls);
        // Abstract class → #[interface] annotation, NOT #[cpp(class = ...)]
        assert!(method_src.contains("#[interface]"));
        assert!(!method_src.contains(r#"cpp(class = "IFoo")"#));
        assert!(method_src.contains("fn process(&self, x: i32) -> i32"));

        // Abstract class should NOT appear as a forward declaration in import_lib!
        let free_src = render_free_module(&decls, "mylib");
        assert!(!free_src.contains("class IFoo;"));
    }

    #[test]
    fn render_import_class_concrete_with_virtual_uses_cpp_annotation() {
        // Non-abstract class with a (non-pure) virtual method: should still use
        // #[cpp(class = "...")] and include the method normally.
        let method = FunctionIR {
            name: "compute".to_string(),
            rust_name: "compute".to_string(),
            return_type: "int".to_string(),
            rust_return_type: "i32".to_string(),
            params: vec![int_param("x")],
            qualified_name: "Base::compute".to_string(),
            cpp_signature: "int Base::compute(int) const".to_string(),
            is_const: true,
            is_static: false,
            is_virtual: true,
            is_pure: false,
            class_name: Some("Base".to_string()),
        };
        let class = ClassIR {
            name: "Base".to_string(),
            qualified_name: "Base".to_string(),
            methods: vec![method],
            is_abstract: false,
        };
        let decls = ExtractedDecls {
            functions: vec![],
            classes: vec![class],
            skipped: vec![],
        };

        let method_src = render_method_module(&decls);
        assert!(!method_src.contains("#[interface]"));
        assert!(method_src.contains(r#"cpp(class = "Base")"#));
        assert!(method_src.contains("fn compute(&self, x: i32) -> i32"));

        // Concrete class IS forward-declared in import_lib!
        let free_src = render_free_module(&decls, "mylib");
        assert!(free_src.contains("class Base;"));
    }
}
