use crate::ast::{collect_feature_hints, ClassDecl, ConstructorDecl, EnumDecl, FunctionDecl, MethodDecl, ParameterDecl, TranslationUnit};
use crate::error::Result;
use crate::layout::{relative_display, sanitize_feature_name, FeatureLayout};
use std::collections::HashMap;
use std::fs;

pub fn generate_feature_project(layout: &FeatureLayout, units: &[TranslationUnit]) -> Result<()> {
    fs::create_dir_all(&layout.rust_src_dir)?;
    fs::write(layout.rust_dir.join("Cargo.toml"), render_generated_cargo_toml(&layout.feature))?;
    fs::write(layout.rust_dir.join("build.rs"), render_build_rs(&layout.feature))?;

    let mut modules = Vec::new();
    let mut report = String::from("# init interface report\n\n");
    for unit in units {
        let module_name = &unit.module_name;
        modules.push(module_name.clone());
        let module_dir = layout.rust_src_dir.join(module_name);
        fs::create_dir_all(&module_dir)?;
        let source_text = fs::read_to_string(&unit.source_path).unwrap_or_default();
        fs::write(module_dir.join("mod.rs"), render_module(layout, unit, &source_text))?;
        fs::write(module_dir.join("types.rs"), render_types(unit))?;
        report.push_str(&format!("## {}\n- source: `{}`\n- functions: {}\n- classes: {}\n- enums: {}\n- aliases: {}\n\n", module_name, relative_display(&unit.source_path), unit.functions.len(), unit.classes.len(), unit.enums.len(), unit.type_aliases.len()));
    }
    fs::write(layout.rust_src_dir.join("lib.rs"), render_root_lib(&modules))?;
    fs::write(layout.init_report_path(), report)?;
    Ok(())
}

pub fn render_generated_cargo_toml(feature_name: &str) -> String {
    let pkg = sanitize_feature_name(feature_name);
    // hicc is not published to crates.io; it is available at
    //   https://gitcode.com/xuanwu/hicc
    // Update the path below to point at your local checkout of hicc.
    format!(
        r#"[package]
name = "{pkg}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
# hicc is sourced from https://gitcode.com/xuanwu/hicc — update the path below.
hicc = {{ path = "/path/to/hicc/hicc", version = "0.2" }}

[build-dependencies]
hicc-build = {{ path = "/path/to/hicc/hicc-build", version = "0.2" }}
"#
    )
}

pub fn render_build_rs(feature_name: &str) -> String {
    let name = sanitize_feature_name(feature_name);
    format!(
        "fn main() {{\n    hicc_build::Build::new()\n        .rust_file(\"src/lib.rs\")\n        .compile(\"{name}\");\n    println!(\"cargo::rustc-link-lib={name}\");\n    #[cfg(not(all(target_os = \"windows\", target_env = \"msvc\")))]\n    println!(\"cargo::rustc-link-lib=stdc++\");\n    println!(\"cargo::rerun-if-changed=src/lib.rs\");\n}}\n"
    )
}

pub fn render_root_lib(modules: &[String]) -> String {
    let mut out = String::from("// generated by cpp2rust-demo\n\n");
    for module in modules {
        out.push_str(&format!("pub mod {module};\n"));
    }
    out
}

pub fn render_module(layout: &FeatureLayout, unit: &TranslationUnit, source_text: &str) -> String {
    let hints = collect_feature_hints(unit, source_text);
    let mut out = String::from("// generated by cpp2rust-demo\n\npub mod types;\npub use types::*;\n\n");
    out.push_str("hicc::cpp! {\n");
    out.push_str(&format!("    #include \"{}\"\n", relative_display(&unit.source_path)));
    out.push_str(&render_cpp_helpers(unit, &hints));
    out.push_str("}\n\n");

    out.push_str("hicc::import_class! {\n");
    for class in &unit.classes {
        out.push_str(&render_class_decl(class));
    }
    out.push_str("}\n\n");

    out.push_str("hicc::import_lib! {\n");
    out.push_str(&format!("    #![link_name = \"{}\"]\n\n", sanitize_feature_name(&layout.feature)));
    for class in &unit.classes {
        out.push_str(&format!("    class {};\n", simple_cpp_name(&class.qualified_name)));
    }
    if !unit.classes.is_empty() {
        out.push('\n');
    }

    let mut used_names = HashMap::<String, usize>::new();
    for class in &unit.classes {
        if let Some(constructor) = class.constructors.first() {
            out.push_str(&render_constructor_fn(class, constructor, &mut used_names));
        }
        for method in class.methods.iter().filter(|method| method.is_static) {
            out.push_str(&render_static_method_fn(class, method, &mut used_names));
        }
    }
    for function in &unit.functions {
        out.push_str(&render_global_fn(function, &mut used_names));
    }
    out.push_str(&render_feature_comments(&hints));
    out.push_str("}\n");
    out
}

fn render_types(unit: &TranslationUnit) -> String {
    let mut out = String::from("// generated by cpp2rust-demo\n\n");
    for alias in &unit.type_aliases {
        out.push_str(&format!("pub type {} = {};\n", rust_type_name(&alias.name), map_cpp_type(&alias.underlying_type, TypePosition::Alias)));
    }
    if !unit.type_aliases.is_empty() && !unit.enums.is_empty() {
        out.push('\n');
    }
    for enm in &unit.enums {
        out.push_str(&render_enum(enm));
    }
    out
}

fn render_cpp_helpers(unit: &TranslationUnit, hints: &indexmap::IndexMap<&'static str, bool>) -> String {
    let mut out = String::new();
    for class in &unit.classes {
        for method in class.methods.iter().filter(|method| method.name.starts_with("operator")) {
            let helper_name = operator_helper_name(&class.name, &method.name);
            let args = method
                .params
                .iter()
                .enumerate()
                .map(|(index, param)| format!("{} arg{index}", param.qual_type))
                .collect::<Vec<_>>();
            let call_args = (0..method.params.len())
                .map(|index| format!("arg{index}"))
                .collect::<Vec<_>>()
                .join(", ");
            let op_suffix = method.name.trim_start_matches("operator");
            out.push_str(&format!("    static auto {helper_name}(const {class_name}& self{maybe_comma}{args}) {{ return self {op_suffix} {call_args}; }}\n", class_name = class.qualified_name, maybe_comma = if args.is_empty() { "" } else { ", " }, args = args.join(", ")));
        }
    }
    if hints["dynamic_cast"] {
        out.push_str("    // dynamic_cast support available through generated @dynamic_cast bindings.\n");
    }
    if hints["placement_new"] {
        out.push_str("    // placement new support available through generated @placement_new bindings.\n");
    }
    out
}

fn render_class_decl(class: &ClassDecl) -> String {
    let mut out = String::new();
    if class.is_abstract {
        out.push_str("    #[interface]\n");
    } else if let Some(constructor) = class.constructors.first() {
        out.push_str(&format!("    #[cpp(class = \"{}\", ctor = \"{}({})\")]\n", class.qualified_name, simple_cpp_name(&class.qualified_name), cpp_param_list(&constructor.params)));
    } else {
        out.push_str(&format!("    #[cpp(class = \"{}\")]\n", class.qualified_name));
    }
    out.push_str(&format!("    class {}{} {{\n", simple_cpp_name(&class.qualified_name), render_bases(&class.bases)));
    let mut emitted = 0usize;
    for method in class.methods.iter().filter(|method| !method.is_static) {
        out.push_str(&render_method(method));
        emitted += 1;
    }
    if emitted == 0 {
        out.push_str("    }\n\n");
    } else {
        out.push_str("    }\n\n");
    }
    out
}

fn render_method(method: &MethodDecl) -> String {
    let receiver = if method.ref_qualifier.as_deref() == Some("&&") {
        "self".to_string()
    } else if method.is_const {
        "&self".to_string()
    } else {
        "&mut self".to_string()
    };
    let rust_name = rust_method_name(&method.name);
    let args = method
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| format!("arg{index}: {}", map_cpp_type(&param.qual_type, TypePosition::Param)))
        .collect::<Vec<_>>()
        .join(", ");
    let signature_args = cpp_param_list(&method.params);
    let qualifiers = if method.is_const && method.is_volatile {
        " const volatile"
    } else if method.is_const {
        " const"
    } else if method.is_volatile {
        " volatile"
    } else {
        ""
    };
    let ref_qual = method.ref_qualifier.as_deref().unwrap_or("");
    let return_type = map_cpp_type(&method.return_type, TypePosition::Return);
    let return_type = if method.throws {
        format!("hicc::Exception<{return_type}>")
    } else {
        return_type
    };
    let ret_suffix = rust_ret_suffix(&return_type);
    if args.is_empty() {
        format!("        #[cpp(method = \"{} {}(){}{}\")]\n        fn {}({}){ret_suffix};\n", method.return_type, method.name, qualifiers, ref_qual, rust_name, receiver)
    } else {
        format!("        #[cpp(method = \"{} {}({}){}{}\")]\n        fn {}({}, {}){ret_suffix};\n", method.return_type, method.name, signature_args, qualifiers, ref_qual, rust_name, receiver, args)
    }
}

fn render_constructor_fn(class: &ClassDecl, constructor: &ConstructorDecl, used_names: &mut HashMap<String, usize>) -> String {
    let fn_name = unique_name(used_names, &format!("{}_new", rust_ident(&class.name)));
    let rust_args = render_rust_params(&constructor.params);
    let template_args = if constructor.params.is_empty() {
        String::new()
    } else {
        format!(", {}", cpp_param_list(&constructor.params))
    };
    let invoke_args = constructor
        .params
        .iter()
        .map(|param| format!("{}&&", param.qual_type))
        .collect::<Vec<_>>()
        .join(", ");
    if constructor.params.is_empty() {
        format!("    #[cpp(func = \"std::unique_ptr<{}> hicc::make_unique<{}>()\")]\n    fn {}() -> {};\n", class.qualified_name, class.qualified_name, fn_name, simple_cpp_name(&class.qualified_name))
    } else {
        format!("    #[cpp(func = \"std::unique_ptr<{}> hicc::make_unique<{}{}>({})\")]\n    fn {}({}) -> {};\n", class.qualified_name, class.qualified_name, template_args, invoke_args, fn_name, rust_args, simple_cpp_name(&class.qualified_name))
    }
}

fn render_static_method_fn(class: &ClassDecl, method: &MethodDecl, used_names: &mut HashMap<String, usize>) -> String {
    let rust_name = unique_name(used_names, &format!("{}_{}", rust_ident(&class.name), rust_method_name(&method.name)));
    let args = render_rust_params(&method.params);
    let cpp_args = cpp_param_list(&method.params);
    let return_type = map_cpp_type(&method.return_type, TypePosition::Return);
    let ret_suffix = rust_ret_suffix(&return_type);
    format!("    #[cpp(func = \"{} {}::{}({})\")]\n    fn {}({}){ret_suffix};\n", method.return_type, class.qualified_name, method.name, cpp_args, rust_name, args)
}

fn render_global_fn(function: &FunctionDecl, used_names: &mut HashMap<String, usize>) -> String {
    let rust_name = unique_name(used_names, &rust_ident(&function.name));
    let args = render_rust_params(&function.params);
    let cpp_args = cpp_param_list(&function.params);
    let return_type = map_cpp_type(&function.return_type, TypePosition::Return);
    let ret_suffix = rust_ret_suffix(&return_type);
    if args.is_empty() {
        format!("    #[cpp(func = \"{} {}()\")]\n    fn {}(){ret_suffix};\n", function.return_type, function.qualified_name, rust_name)
    } else {
        format!("    #[cpp(func = \"{} {}({})\")]\n    fn {}({}){ret_suffix};\n", function.return_type, function.qualified_name, cpp_args, rust_name, args)
    }
}

fn render_feature_comments(hints: &indexmap::IndexMap<&'static str, bool>) -> String {
    let mut out = String::new();
    if hints["dynamic_cast"] {
        out.push_str("    // dynamic_cast: emit #[cpp(func = \"Dst* @dynamic_cast<Dst*>(Src*)\")] helpers as needed.\n");
    }
    if hints["placement_new"] {
        out.push_str("    // placement_new: emit #[cpp(func = \"hicc::AbiClass<T> @placement_new<T, Args...>(void*, size_t, Args...)\")] helpers as needed.\n");
    }
    if hints["std_function"] {
        out.push_str("    // std::function maps to hicc::Function<fn(...) -> ...>.\n");
    }
    if hints["stl_containers"] {
        out.push_str("    // STL containers should use hicc_std wrappers or be reviewed manually.\n");
    }
    if hints["smart_pointers"] {
        out.push_str("    // Smart pointers use hicc::unique_ptr / hicc::shared_ptr semantics where applicable.\n");
    }
    out
}

fn render_enum(enm: &EnumDecl) -> String {
    let rust_name = rust_type_name(&enm.name);
    let mut out = format!("pub type {rust_name} = i32;\n");
    for variant in &enm.variants {
        if let Some(value) = &variant.value {
            out.push_str(&format!("pub const {}_{}: {rust_name} = {};\n", rust_name.to_uppercase(), variant.name.to_uppercase(), value));
        }
    }
    out.push('\n');
    out
}

fn render_bases(bases: &[String]) -> String {
    let names = bases
        .iter()
        .map(|base| simple_cpp_name(base))
        .collect::<Vec<_>>();
    if names.is_empty() {
        String::new()
    } else {
        format!(": {}", names.join(", "))
    }
}

#[derive(Clone, Copy)]
enum TypePosition {
    Param,
    Return,
    Alias,
}

fn map_cpp_type(cpp_type: &str, position: TypePosition) -> String {
    let ty = cpp_type.trim();
    let normalized = ty.replace("class ", "").replace("struct ", "");
    let normalized = normalized.trim();
    match normalized {
        "int" => "i32".into(),
        "unsigned int" => "u32".into(),
        "long" | "long int" => "i64".into(),
        "unsigned long" | "unsigned long int" => "u64".into(),
        "long long" | "long long int" => "i64".into(),
        "short" | "short int" => "i16".into(),
        "char" | "signed char" => "i8".into(),
        "unsigned char" => "u8".into(),
        "float" => "f32".into(),
        "double" => "f64".into(),
        "bool" => "bool".into(),
        "void" => "()".into(),
        "size_t" | "std::size_t" => "usize".into(),
        "const char *" | "const char*" => "*const u8".into(),
        "char *" | "char*" => "*mut u8".into(),
        "void *" | "void*" => "*mut std::ffi::c_void".into(),
        "const void *" | "const void*" => "*const std::ffi::c_void".into(),
        _ => map_complex_type(normalized, position),
    }
}

fn map_complex_type(cpp_type: &str, position: TypePosition) -> String {
    if let Some(inner) = strip_wrapper(cpp_type, "std::unique_ptr<") {
        return simple_cpp_name(inner);
    }
    if let Some(inner) = strip_wrapper(cpp_type, "std::shared_ptr<") {
        return format!("hicc::shared_ptr<{}>", map_cpp_type(inner, position));
    }
    if let Some(inner) = strip_wrapper(cpp_type, "std::function<") {
        return format!("hicc::Function<{}>", render_function_signature(inner));
    }
    if cpp_type.ends_with("&&") {
        return map_cpp_type(cpp_type.trim_end_matches("&&").trim(), position);
    }
    if cpp_type.ends_with('&') {
        let inner = cpp_type.trim_end_matches('&').trim();
        if inner.starts_with("const ") {
            return format!("&{}", simple_cpp_name(inner.trim_start_matches("const ").trim()));
        }
        return format!("&mut {}", simple_cpp_name(inner));
    }
    if cpp_type.ends_with('*') {
        let inner = cpp_type.trim_end_matches('*').trim();
        if inner.starts_with("const ") {
            let base = inner.trim_start_matches("const ").trim();
            return if is_primitive(base) {
                format!("*const {}", map_cpp_type(base, position))
            } else {
                match position {
                    TypePosition::Return => format!("hicc::ClassPtr<'static, {}>", simple_cpp_name(base)),
                    _ => format!("&{}", simple_cpp_name(base)),
                }
            };
        }
        return if is_primitive(inner) {
            format!("*mut {}", map_cpp_type(inner, position))
        } else {
            match position {
                TypePosition::Return => format!("hicc::ClassMutPtr<'static, {}>", simple_cpp_name(inner)),
                _ => format!("&mut {}", simple_cpp_name(inner)),
            }
        };
    }
    simple_cpp_name(cpp_type)
}

fn strip_wrapper<'a>(ty: &'a str, prefix: &str) -> Option<&'a str> {
    if ty.starts_with(prefix) && ty.ends_with('>') {
        Some(&ty[prefix.len()..ty.len() - 1])
    } else {
        None
    }
}

fn render_function_signature(signature: &str) -> String {
    let signature = signature.trim();
    if let Some((ret, args)) = signature.split_once('(') {
        let args = args.trim_end_matches(')');
        let mapped_args = if args.trim().is_empty() {
            String::new()
        } else {
            args.split(',')
                .map(|arg| map_cpp_type(arg.trim(), TypePosition::Param))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let ret = map_cpp_type(ret.trim(), TypePosition::Return);
        format!("fn({mapped_args}) -> {ret}")
    } else {
        "fn()".into()
    }
}

fn is_primitive(ty: &str) -> bool {
    matches!(ty.trim(), "int" | "unsigned int" | "long" | "unsigned long" | "long long" | "short" | "char" | "unsigned char" | "float" | "double" | "bool" | "size_t" | "std::size_t")
}

fn render_rust_params(params: &[ParameterDecl]) -> String {
    params
        .iter()
        .enumerate()
        .map(|(index, param)| format!("arg{index}: {}", map_cpp_type(&param.qual_type, TypePosition::Param)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn cpp_param_list(params: &[ParameterDecl]) -> String {
    params
        .iter()
        .map(|param| param.qual_type.clone())
        .collect::<Vec<_>>()
        .join(", ")
}

fn rust_method_name(name: &str) -> String {
    rust_ident(&name.replace("operator", "operator_"))
}

fn rust_type_name(name: &str) -> String {
    simple_cpp_name(name).replace(':', "_")
}

fn rust_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    match out.as_str() {
        "fn" | "struct" | "type" | "mod" | "move" | "self" | "crate" => format!("r#{out}"),
        _ => out,
    }
}

fn simple_cpp_name(name: &str) -> String {
    name.split("::").last().unwrap_or(name).trim().to_string()
}

fn unique_name(used_names: &mut HashMap<String, usize>, base: &str) -> String {
    let entry = used_names.entry(base.to_string()).or_insert(0);
    if *entry == 0 {
        *entry = 1;
        base.to_string()
    } else {
        let value = *entry;
        *entry += 1;
        format!("{base}_{value}")
    }
}

fn operator_helper_name(class_name: &str, method_name: &str) -> String {
    format!("{}_{}", rust_ident(class_name), rust_ident(method_name))
}

/// Returns ` -> T` for non-void Rust return types, or empty string for `()`.
fn rust_ret_suffix(rust_type: &str) -> String {
    if rust_type == "()" {
        String::new()
    } else {
        format!(" -> {rust_type}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ClassDecl, MethodDecl, TranslationUnit};

    fn test_dir(name: &str) -> std::path::PathBuf {
        let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target/test-work/codegen")
            .join(format!("{name}-{}", std::process::id()));
        if root.exists() {
            std::fs::remove_dir_all(&root).unwrap();
        }
        std::fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn maps_basic_cpp_types() {
        assert_eq!(map_cpp_type("int", TypePosition::Param), "i32");
        assert_eq!(map_cpp_type("const char*", TypePosition::Param), "*const u8");
        assert_eq!(map_cpp_type("std::unique_ptr<Foo>", TypePosition::Return), "Foo");
    }

    #[test]
    fn void_return_omits_arrow() {
        assert_eq!(rust_ret_suffix("()"), "");
        assert_eq!(rust_ret_suffix("i32"), " -> i32");
    }

    #[test]
    fn renders_root_lib() {
        let lib = render_root_lib(&["alpha".into(), "beta".into()]);
        assert!(lib.contains("pub mod alpha;"));
        assert!(lib.contains("pub mod beta;"));
    }

    #[test]
    fn renders_class_with_interface() {
        let class = ClassDecl {
            name: "Shape".into(),
            qualified_name: "Shape".into(),
            is_abstract: true,
            methods: vec![MethodDecl {
                name: "area".into(),
                return_type: "double".into(),
                is_const: true,
                ..MethodDecl::default()
            }],
            ..ClassDecl::default()
        };
        let rendered = render_class_decl(&class);
        assert!(rendered.contains("#[interface]"));
        assert!(rendered.contains("fn area(&self) -> f64;"));
    }

    #[test]
    fn generates_feature_project_files() {
        let dir = test_dir("project");
        let layout = FeatureLayout::new(&dir, "demo");
        layout.ensure_dirs().unwrap();
        let source = dir.join("main.cpp");
        fs::write(&source, "int add(int a, int b) { return a + b; }").unwrap();
        let unit = TranslationUnit {
            source_path: source,
            module_name: "main".into(),
            functions: vec![FunctionDecl {
                name: "add".into(),
                qualified_name: "add".into(),
                return_type: "int".into(),
                params: vec![
                    ParameterDecl { name: "a".into(), qual_type: "int".into() },
                    ParameterDecl { name: "b".into(), qual_type: "int".into() },
                ],
                ..FunctionDecl::default()
            }],
            ..TranslationUnit::default()
        };
        generate_feature_project(&layout, &[unit]).unwrap();
        assert!(layout.rust_dir.join("Cargo.toml").exists());
        assert!(layout.rust_src_dir.join("main/mod.rs").exists());
        assert!(layout.rust_src_dir.join("lib.rs").exists());
    }
}
