use crate::ast::{collect_feature_hints, ClassDecl, ConstructorDecl, EnumDecl, FunctionDecl, MethodDecl, ParameterDecl, TranslationUnit};
use crate::error::Result;
use crate::layout::{relative_display, sanitize_feature_name, FeatureLayout};
use std::collections::HashMap;
use std::fs;

pub fn generate_feature_project(layout: &FeatureLayout, units: &[TranslationUnit]) -> Result<()> {
    fs::create_dir_all(&layout.rust_src_dir)?;
    fs::write(layout.rust_dir.join("Cargo.toml"), render_generated_cargo_toml(&layout.feature))?;
    fs::write(layout.rust_dir.join("build.rs"), render_build_rs(&layout.feature))?;

    let mut modules = Vec::new();
    let mut report = String::from("# init interface report\n\n");
    for unit in units {
        let module_name = &unit.module_name;
        modules.push(module_name.clone());
        let module_dir = layout.rust_src_dir.join(module_name);
        fs::create_dir_all(&module_dir)?;
        let source_text = fs::read_to_string(&unit.source_path).unwrap_or_default();
        fs::write(module_dir.join("mod.rs"), render_module(layout, unit, &source_text))?;
        fs::write(module_dir.join("types.rs"), render_types(unit))?;
        report.push_str(&format!("## {}\n- source: `{}`\n- functions: {}\n- classes: {}\n- enums: {}\n- aliases: {}\n\n", module_name, relative_display(&unit.source_path), unit.functions.len(), unit.classes.len(), unit.enums.len(), unit.type_aliases.len()));
    }
    fs::write(layout.rust_src_dir.join("lib.rs"), render_root_lib(&modules))?;
    fs::write(layout.init_report_path(), report)?;
    Ok(())
}

pub fn render_generated_cargo_toml(feature_name: &str) -> String {
    let pkg = sanitize_feature_name(feature_name);
    format!(
        "[package]\nname = \"{pkg}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\ncrate-type = [\"staticlib\"]\n\n[dependencies]\nhicc = \"0.2\"\n\n[build-dependencies]\nhicc-build = \"0.2\"\n"
    )
}

pub fn render_build_rs(feature_name: &str) -> String {
    let name = sanitize_feature_name(feature_name);
    format!(
        "fn main() {{\n    hicc_build::Build::new()\n        .rust_file(\"src/lib.rs\")\n        .compile(\"{name}\");\n    println!(\"cargo::rustc-link-lib={name}\");\n    #[cfg(not(all(target_os = \"windows\", target_env = \"msvc\")))]\n    println!(\"cargo::rustc-link-lib=stdc++\");\n    println!(\"cargo::rerun-if-changed=src/lib.rs\");\n}}\n"
    )
}

pub fn render_root_lib(modules: &[String]) -> String {
    let mut out = String::from("// generated by cpp2rust-demo\n\n");
    for module in modules {
        out.push_str(&format!("pub mod {module};\n"));
    }
    out
}

pub fn render_module(layout: &FeatureLayout, unit: &TranslationUnit, source_text: &str) -> String {
    let hints = collect_feature_hints(unit, source_text);
    let mut out = String::from("// generated by cpp2rust-demo\n\npub mod types;\npub use types::*;\n\n");
    out.push_str("hicc::cpp! {\n");
    out.push_str(&format!("    #include \"{}\"\n", relative_display(&unit.source_path)));
    out.push_str(&render_cpp_helpers(unit, &hints));
    out.push_str("}\n\n");

    // Build set of abstract (interface) class simple names for base-class filtering.
    let known_abstract: std::collections::HashSet<String> = unit
        .classes
        .iter()
        .filter(|c| c.is_abstract)
        .map(|c| simple_cpp_name(&c.qualified_name))
        .collect();

    // Build map from abstract class name → set of Rust method names it declares.
    // Concrete subclasses must NOT re-declare these (the macro inherits them).
    // Self-referencing methods (those skipped in the interface due to E0782) are excluded.
    let abstract_methods: std::collections::HashMap<String, std::collections::HashSet<String>> = unit
        .classes
        .iter()
        .filter(|c| c.is_abstract)
        .map(|c| {
            let own_simple = simple_cpp_name(&c.qualified_name);
            let method_names = c
                .methods
                .iter()
                .filter(|m| !m.is_static && !m.is_template)
                .filter(|m| {
                    // Skip self-referencing methods (would be dropped from the interface block)
                    let uses_self = m.return_type.contains(&own_simple)
                        || m.params.iter().any(|p| p.qual_type.contains(&own_simple));
                    !uses_self
                })
                .map(|m| rust_method_name(&m.name))
                .collect();
            (own_simple, method_names)
        })
        .collect();

    // Non-template classes only.
    let visible_classes: Vec<&ClassDecl> = unit.classes.iter().filter(|c| !c.is_template).collect();

    out.push_str("hicc::import_class! {\n");
    for class in &visible_classes {
        out.push_str(&render_class_decl(class, &known_abstract, &abstract_methods));
    }
    out.push_str("}\n\n");

    out.push_str("hicc::import_lib! {\n");
    out.push_str(&format!("    #![link_name = \"{}\"]\n\n", sanitize_feature_name(&layout.feature)));
    for class in &visible_classes {
        out.push_str(&format!("    class {};\n", simple_cpp_name(&class.qualified_name)));
    }
    if !visible_classes.is_empty() {
        out.push('\n');
    }

    let mut used_names = HashMap::<String, usize>::new();
    for class in &visible_classes {
        // Abstract (interface) classes cannot be instantiated; skip their constructors.
        if class.is_abstract {
            continue;
        }
        if let Some(constructor) = class.constructors.first() {
            // Also skip if any constructor parameter type references an abstract class.
            let uses_abstract = constructor.params.iter().any(|p| {
                known_abstract.iter().any(|a| p.qual_type.contains(a.as_str()))
            });
            if !uses_abstract && !has_unmappable_types(&class.qualified_name, &constructor.params) {
                out.push_str(&render_constructor_fn(class, constructor, &mut used_names));
            }
        }
        for method in class.methods.iter().filter(|m| m.is_static && !m.is_template) {
            if !has_unmappable_types(&method.return_type, &method.params) {
                out.push_str(&render_static_method_fn(class, method, &mut used_names));
            }
        }
    }
    for function in unit.functions.iter().filter(|f| !f.is_template) {
        if !has_unmappable_types(&function.return_type, &function.params)
            && !has_abstract_types(&function.return_type, &function.params, &known_abstract)
        {
            out.push_str(&render_global_fn(function, &mut used_names));
        }
    }
    out.push_str(&render_feature_comments(&hints));
    out.push_str("}\n");
    out
}

fn render_types(unit: &TranslationUnit) -> String {
    let mut out = String::from("// generated by cpp2rust-demo\n\n");
    for alias in &unit.type_aliases {
        out.push_str(&format!("pub type {} = {};\n", rust_type_name(&alias.name), map_cpp_type(&alias.underlying_type, TypePosition::Alias)));
    }
    if !unit.type_aliases.is_empty() && !unit.enums.is_empty() {
        out.push('\n');
    }
    for enm in &unit.enums {
        out.push_str(&render_enum(enm));
    }
    out
}

fn render_cpp_helpers(unit: &TranslationUnit, hints: &indexmap::IndexMap<&'static str, bool>) -> String {
    let mut out = String::new();
    for class in &unit.classes {
        for method in class.methods.iter().filter(|method| method.name.starts_with("operator")) {
            let helper_name = operator_helper_name(&class.name, &method.name);
            let args = method
                .params
                .iter()
                .enumerate()
                .map(|(index, param)| format!("{} arg{index}", param.qual_type))
                .collect::<Vec<_>>();
            let call_args = (0..method.params.len())
                .map(|index| format!("arg{index}"))
                .collect::<Vec<_>>()
                .join(", ");
            let op_suffix = method.name.trim_start_matches("operator");
            out.push_str(&format!("    static auto {helper_name}(const {class_name}& self{maybe_comma}{args}) {{ return self {op_suffix} {call_args}; }}\n", class_name = class.qualified_name, maybe_comma = if args.is_empty() { "" } else { ", " }, args = args.join(", ")));
        }
    }
    if hints["dynamic_cast"] {
        out.push_str("    // dynamic_cast support available through generated @dynamic_cast bindings.\n");
    }
    if hints["placement_new"] {
        out.push_str("    // placement new support available through generated @placement_new bindings.\n");
    }
    out
}

fn render_class_decl(class: &ClassDecl, known_abstract: &std::collections::HashSet<String>, abstract_methods: &std::collections::HashMap<String, std::collections::HashSet<String>>) -> String {
    let mut out = String::new();
    if class.is_abstract {
        out.push_str("    #[interface]\n");
    } else if let Some(constructor) = class.constructors.first() {
        out.push_str(&format!("    #[cpp(class = \"{}\", ctor = \"{}({})\")]\n", class.qualified_name, simple_cpp_name(&class.qualified_name), cpp_param_list(&constructor.params)));
    } else {
        out.push_str(&format!("    #[cpp(class = \"{}\")]\n", class.qualified_name));
    }
    let base_str = render_bases(&class.bases, known_abstract);
    out.push_str(&format!("    class {}{} {{\n", simple_cpp_name(&class.qualified_name), base_str));
    let mut method_names = HashMap::<String, usize>::new();

    // If this concrete class extends an abstract (interface) base, skip methods that
    // are already declared in that base — the macro inherits them automatically.
    let inherited_names: std::collections::HashSet<String> = if !class.is_abstract {
        // Extract just the class name from ": ClassName"
        if let Some(base_name) = base_str.strip_prefix(": ") {
            abstract_methods.get(base_name).cloned().unwrap_or_default()
        } else {
            std::collections::HashSet::new()
        }
    } else {
        std::collections::HashSet::new()
    };

    let own_simple_name = simple_cpp_name(&class.qualified_name);
    for method in class.methods.iter().filter(|m| !m.is_static && !m.is_template) {
        let rust_name = rust_method_name(&method.name);
        if inherited_names.contains(&rust_name) {
            // pre-register the name so that overloads still get unique suffixes
            let _ = unique_name(&mut method_names, &rust_name);
            continue;
        }
        // For abstract (interface) classes, skip methods whose parameters or return type
        // reference the class itself. Since the class becomes a Rust trait, using it as
        // a concrete type in `&Self` position is invalid (E0782).
        if class.is_abstract {
            let uses_self_type = method.return_type.contains(&own_simple_name)
                || method.params.iter().any(|p| p.qual_type.contains(&own_simple_name));
            if uses_self_type {
                continue;
            }
            // Also skip if the method references any other abstract class (they are also traits)
            if has_abstract_types(&method.return_type, &method.params, known_abstract) {
                continue;
            }
        }
        // For concrete classes, skip methods that reference abstract classes as types —
        // those would expand to trait types (E0782) in import_class! method signatures.
        if !class.is_abstract && has_abstract_types(&method.return_type, &method.params, known_abstract) {
            continue;
        }
        out.push_str(&render_method(method, &mut method_names));
    }
    out.push_str("    }\n\n");
    out
}

fn render_method(method: &MethodDecl, used_names: &mut HashMap<String, usize>) -> String {
    let receiver = if method.ref_qualifier.as_deref() == Some("&&") {
        "self".to_string()
    } else if method.is_const {
        "&self".to_string()
    } else {
        "&mut self".to_string()
    };
    let rust_name = unique_name(used_names, &rust_method_name(&method.name));
    let args = method
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| format!("arg{index}: {}", map_cpp_type(&param.qual_type, TypePosition::Param)))
        .collect::<Vec<_>>()
        .join(", ");
    let signature_args = cpp_param_list(&method.params);
    let qualifiers = if method.is_const && method.is_volatile {
        " const volatile"
    } else if method.is_const {
        " const"
    } else if method.is_volatile {
        " volatile"
    } else {
        ""
    };
    let ref_qual = method.ref_qualifier.as_deref().unwrap_or("");
    let return_type = map_cpp_type(&method.return_type, TypePosition::Return);
    let return_type = if method.throws {
        format!("hicc::Exception<{return_type}>")
    } else {
        return_type
    };
    let ret_suffix = rust_ret_suffix(&return_type);
    if args.is_empty() {
        format!("        #[cpp(method = \"{} {}(){}{}\")]\n        fn {}({}){ret_suffix};\n", method.return_type, method.name, qualifiers, ref_qual, rust_name, receiver)
    } else {
        format!("        #[cpp(method = \"{} {}({}){}{}\")]\n        fn {}({}, {}){ret_suffix};\n", method.return_type, method.name, signature_args, qualifiers, ref_qual, rust_name, receiver, args)
    }
}

fn render_constructor_fn(class: &ClassDecl, constructor: &ConstructorDecl, used_names: &mut HashMap<String, usize>) -> String {
    let fn_name = unique_name(used_names, &format!("{}_new", rust_ident(&class.name)));
    let rust_args = render_rust_params(&constructor.params);
    let template_args = if constructor.params.is_empty() {
        String::new()
    } else {
        format!(", {}", cpp_param_list(&constructor.params))
    };
    let invoke_args = constructor
        .params
        .iter()
        .map(|param| format!("{}&&", param.qual_type))
        .collect::<Vec<_>>()
        .join(", ");
    if constructor.params.is_empty() {
        format!("    #[cpp(func = \"std::unique_ptr<{}> hicc::make_unique<{}>()\")]\n    fn {}() -> {};\n", class.qualified_name, class.qualified_name, fn_name, simple_cpp_name(&class.qualified_name))
    } else {
        format!("    #[cpp(func = \"std::unique_ptr<{}> hicc::make_unique<{}{}>({})\")]\n    fn {}({}) -> {};\n", class.qualified_name, class.qualified_name, template_args, invoke_args, fn_name, rust_args, simple_cpp_name(&class.qualified_name))
    }
}

fn render_static_method_fn(class: &ClassDecl, method: &MethodDecl, used_names: &mut HashMap<String, usize>) -> String {
    let rust_name = unique_name(used_names, &format!("{}_{}", rust_ident(&class.name), rust_method_name(&method.name)));
    let args = render_rust_params(&method.params);
    let cpp_args = cpp_param_list(&method.params);
    let return_type = map_cpp_type(&method.return_type, TypePosition::Return);
    let ret_suffix = rust_ret_suffix(&return_type);
    format!("    #[cpp(func = \"{} {}::{}({})\")]\n    fn {}({}){ret_suffix};\n", method.return_type, class.qualified_name, method.name, cpp_args, rust_name, args)
}

fn render_global_fn(function: &FunctionDecl, used_names: &mut HashMap<String, usize>) -> String {
    let rust_name = unique_name(used_names, &rust_ident(&function.name));
    let args = render_rust_params(&function.params);
    let cpp_args = cpp_param_list(&function.params);
    let return_type = map_cpp_type(&function.return_type, TypePosition::Return);
    let ret_suffix = rust_ret_suffix(&return_type);
    if args.is_empty() {
        format!("    #[cpp(func = \"{} {}()\")]\n    fn {}(){ret_suffix};\n", function.return_type, function.qualified_name, rust_name)
    } else {
        format!("    #[cpp(func = \"{} {}({})\")]\n    fn {}({}){ret_suffix};\n", function.return_type, function.qualified_name, cpp_args, rust_name, args)
    }
}

fn render_feature_comments(hints: &indexmap::IndexMap<&'static str, bool>) -> String {
    let mut out = String::new();
    if hints["dynamic_cast"] {
        out.push_str("    // dynamic_cast: emit #[cpp(func = \"Dst* @dynamic_cast<Dst*>(Src*)\")] helpers as needed.\n");
    }
    if hints["placement_new"] {
        out.push_str("    // placement_new: emit #[cpp(func = \"hicc::AbiClass<T> @placement_new<T, Args...>(void*, size_t, Args...)\")] helpers as needed.\n");
    }
    if hints["std_function"] {
        out.push_str("    // std::function maps to hicc::Function<fn(...) -> ...>.\n");
    }
    if hints["stl_containers"] {
        out.push_str("    // STL containers should use hicc_std wrappers or be reviewed manually.\n");
    }
    if hints["smart_pointers"] {
        out.push_str("    // Smart pointers use hicc::unique_ptr / hicc::shared_ptr semantics where applicable.\n");
    }
    out
}

fn render_enum(enm: &EnumDecl) -> String {
    let rust_name = rust_type_name(&enm.name);
    let mut out = format!("pub type {rust_name} = i32;\n");
    for variant in &enm.variants {
        if let Some(value) = &variant.value {
            out.push_str(&format!("pub const {}_{}: {rust_name} = {};\n", rust_name.to_uppercase(), variant.name.to_uppercase(), value));
        }
    }
    out.push('\n');
    out
}

fn render_bases(bases: &[String], known_abstract: &std::collections::HashSet<String>) -> String {
    // import_class! only supports extending a single #[interface] (abstract) base.
    // Skip bases that are not locally declared abstract classes.
    let name = bases
        .iter()
        .map(|base| simple_cpp_name(base))
        .find(|n| known_abstract.contains(n));
    match name {
        Some(n) => format!(": {n}"),
        None => String::new(),
    }
}

#[derive(Clone, Copy)]
enum TypePosition {
    Param,
    Return,
    Alias,
}

fn map_cpp_type(cpp_type: &str, position: TypePosition) -> String {
    let ty = cpp_type.trim();
    let normalized = ty.replace("class ", "").replace("struct ", "");
    let normalized = normalized.trim();
    match normalized {
        "int" | "signed int" => "i32".into(),
        "unsigned int" | "uint" => "u32".into(),
        "long" | "long int" | "signed long" | "signed long int" => "i64".into(),
        "unsigned long" | "unsigned long int" => "u64".into(),
        "long long" | "long long int" | "signed long long" | "signed long long int" => "i64".into(),
        "unsigned long long" | "unsigned long long int" | "long long unsigned int" => "u64".into(),
        "short" | "short int" | "signed short" | "signed short int" => "i16".into(),
        "unsigned short" | "unsigned short int" => "u16".into(),
        "char" | "signed char" => "i8".into(),
        "unsigned char" => "u8".into(),
        "float" => "f32".into(),
        "double" => "f64".into(),
        "bool" => "bool".into(),
        "void" => "()".into(),
        "size_t" | "std::size_t" => "usize".into(),
        "intptr_t" | "std::intptr_t" | "ssize_t" => "isize".into(),
        "uintptr_t" | "std::uintptr_t" => "usize".into(),
        "ptrdiff_t" | "std::ptrdiff_t" => "isize".into(),
        "int8_t" | "std::int8_t" => "i8".into(),
        "uint8_t" | "std::uint8_t" => "u8".into(),
        "int16_t" | "std::int16_t" => "i16".into(),
        "uint16_t" | "std::uint16_t" => "u16".into(),
        "int32_t" | "std::int32_t" => "i32".into(),
        "uint32_t" | "std::uint32_t" => "u32".into(),
        "int64_t" | "std::int64_t" => "i64".into(),
        "uint64_t" | "std::uint64_t" => "u64".into(),
        "const char *" | "const char*" => "*const u8".into(),
        "char *" | "char*" => "*mut u8".into(),
        "void *" | "void*" => "*mut std::ffi::c_void".into(),
        "const void *" | "const void*" => "*const std::ffi::c_void".into(),
        _ => map_complex_type(normalized, position),
    }
}

fn map_complex_type(cpp_type: &str, position: TypePosition) -> String {
    // Normalize "T *const" (const-qualified pointer, e.g. "const Foo *const") → "T *"
    if let Some(base) = cpp_type.strip_suffix("*const") {
        return map_complex_type(&format!("{}*", base.trim_end()), position);
    }

    if let Some(inner) = strip_wrapper(cpp_type, "std::unique_ptr<") {
        return simple_cpp_name(inner);
    }
    if let Some(inner) = strip_wrapper(cpp_type, "unique_ptr<") {
        return simple_cpp_name(inner);
    }
    if let Some(inner) = strip_wrapper(cpp_type, "std::shared_ptr<") {
        return format!("hicc::shared_ptr<{}>", map_cpp_type(inner, position));
    }
    if let Some(inner) = strip_wrapper(cpp_type, "shared_ptr<") {
        return simple_cpp_name(inner);
    }
    if let Some(inner) = strip_wrapper(cpp_type, "std::function<") {
        return format!("hicc::Function<{}>", render_function_signature(inner));
    }

    // Function pointer types: "RetType (*)(ArgTypes...)"
    if let Some(fp_pos) = cpp_type.find("(*)") {
        let ret_str = cpp_type[..fp_pos].trim();
        let after = &cpp_type[fp_pos + 3..];
        let args_str = after.trim_start_matches('(').trim_end_matches(')');
        let ret = map_cpp_type(ret_str, TypePosition::Return);
        let mapped_args = if args_str.trim().is_empty() {
            String::new()
        } else {
            args_str
                .split(',')
                .map(|a| map_cpp_type(a.trim(), TypePosition::Param))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let ret_suffix = if ret == "()" { String::new() } else { format!(" -> {ret}") };
        return format!("Option<unsafe extern \"C\" fn({mapped_args}){ret_suffix}>");
    }

    if cpp_type.ends_with("&&") {
        return map_cpp_type(cpp_type.trim_end_matches("&&").trim(), position);
    }
    if cpp_type.ends_with('&') {
        let inner = cpp_type.trim_end_matches('&').trim();
        let (is_const, base) = if inner.starts_with("const ") {
            (true, inner.trim_start_matches("const ").trim())
        } else {
            (false, inner)
        };
        let mapped_base = if is_primitive(base) {
            map_cpp_type(base, TypePosition::Param)
        } else {
            simple_cpp_name(base)
        };
        return match (is_const, position) {
            // Use raw pointers for reference returns to avoid lifetime annotation issues.
            (true, TypePosition::Return) => format!("*const {mapped_base}"),
            (false, TypePosition::Return) => format!("*mut {mapped_base}"),
            (true, _) => format!("&{mapped_base}"),
            (false, _) => format!("&mut {mapped_base}"),
        };
    }
    if cpp_type.ends_with('*') {
        let inner = cpp_type.trim_end_matches('*').trim();
        if inner.starts_with("const ") {
            let base = inner.trim_start_matches("const ").trim();
            return if is_primitive(base) {
                format!("*const {}", map_cpp_type(base, position))
            } else {
                match position {
                    TypePosition::Return => format!("hicc::ClassPtr<'static, {}>", simple_cpp_name(base)),
                    _ => format!("&{}", simple_cpp_name(base)),
                }
            };
        }
        return if is_primitive(inner) {
            format!("*mut {}", map_cpp_type(inner, position))
        } else {
            match position {
                TypePosition::Return => format!("hicc::ClassMutPtr<'static, {}>", simple_cpp_name(inner)),
                _ => format!("&mut {}", simple_cpp_name(inner)),
            }
        };
    }
    simple_cpp_name(cpp_type)
}

fn strip_wrapper<'a>(ty: &'a str, prefix: &str) -> Option<&'a str> {
    if ty.starts_with(prefix) && ty.ends_with('>') {
        Some(&ty[prefix.len()..ty.len() - 1])
    } else {
        None
    }
}

fn render_function_signature(signature: &str) -> String {
    let signature = signature.trim();
    if let Some((ret, args)) = signature.split_once('(') {
        let args = args.trim_end_matches(')');
        let mapped_args = if args.trim().is_empty() {
            String::new()
        } else {
            args.split(',')
                .map(|arg| map_cpp_type(arg.trim(), TypePosition::Param))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let ret = map_cpp_type(ret.trim(), TypePosition::Return);
        format!("fn({mapped_args}) -> {ret}")
    } else {
        "fn()".into()
    }
}

fn is_primitive(ty: &str) -> bool {
    matches!(
        ty.trim(),
        "int"
            | "signed int"
            | "unsigned int"
            | "long"
            | "unsigned long"
            | "long long"
            | "unsigned long long"
            | "long long unsigned int"
            | "short"
            | "unsigned short"
            | "char"
            | "signed char"
            | "unsigned char"
            | "float"
            | "double"
            | "bool"
            | "size_t"
            | "std::size_t"
            | "intptr_t"
            | "uintptr_t"
            | "ptrdiff_t"
            | "int8_t"
            | "uint8_t"
            | "int16_t"
            | "uint16_t"
            | "int32_t"
            | "uint32_t"
            | "int64_t"
            | "uint64_t"
    )
}

/// Returns `true` for C++ types that cannot be mapped to valid Rust FFI types and
/// whose functions/methods should be omitted from the generated bindings.
fn is_unmappable_cpp_type(cpp_type: &str) -> bool {
    let ty = cpp_type.trim();

    // Empty or auto (deduced/lambda) return types
    if ty.is_empty() || ty == "auto" {
        return true;
    }

    // Variadic template packs
    if ty.contains("...") {
        return true;
    }

    // C++ standard library types that require special handling (typename/decltype)
    if ty.contains("typename") || ty.contains("decltype") || ty.contains("::type") {
        return true;
    }

    // System types without a simple Rust mapping
    if ty.contains("nothrow_t") || ty.contains("align_val_t") || ty.contains("va_list") {
        return true;
    }

    // Lambda types produced by Clang: "(lambda at path/to/file.cpp:line:col)"
    if ty.contains("(lambda") || ty.starts_with("lambda") {
        return true;
    }

    // C++ string types (std::string is not FFI-safe; use *const u8 / CStr at call sites)
    if ty.contains("std::string") || ty.contains("basic_string") || ty == "string" {
        return true;
    }

    // STL sequence/associative containers (not smart pointers)
    const CONTAINER_MARKERS: &[&str] = &[
        "std::vector", "std::list", "std::deque", "std::forward_list",
        "std::map", "std::set", "std::multimap", "std::multiset",
        "std::unordered_map", "std::unordered_set", "std::unordered_multimap",
        "std::priority_queue", "std::stack", "std::queue",
        "std::pair", "std::tuple",
        // Without std:: prefix (after simple_cpp_name stripping)
        "vector<", "list<", "deque<", "map<", "set<", "pair<", "tuple<",
        "multimap<", "unordered_map<", "unordered_set<",
    ];
    for marker in CONTAINER_MARKERS {
        if ty.contains(marker) {
            return true;
        }
    }

    // smart pointer references (by-value smart pointers are OK, references are not)
    if (ty.contains("shared_ptr") || ty.contains("unique_ptr")) && ty.trim_end().ends_with('&') {
        return true;
    }

    // Template parameters: bare single/double uppercase letters (T, U, V, K, etc.)
    let base = strip_type_decorators(ty);
    if !base.is_empty() && base.len() <= 2 && base.chars().all(|c| c.is_ascii_uppercase()) {
        return true;
    }

    false
}

/// Strip qualifiers/decorators from a C++ type to reach the base name.
fn strip_type_decorators(ty: &str) -> &str {
    ty.trim_start_matches("const ")
        .trim()
        .trim_end_matches("&&")
        .trim()
        .trim_end_matches('&')
        .trim()
        .trim_end_matches("*const")
        .trim()
        .trim_end_matches('*')
        .trim()
}

fn has_unmappable_types(return_type: &str, params: &[crate::ast::ParameterDecl]) -> bool {
    is_unmappable_cpp_type(return_type)
        || params.iter().any(|p| is_unmappable_cpp_type(&p.qual_type))
}

/// Returns true if `cpp_type` contains the simple name of any abstract class.
/// Such types map to trait types in Rust (e.g. `&Shape`) which require `dyn` syntax
/// and cannot appear in `import_class!` or `import_lib!` method signatures directly.
fn references_abstract_class(cpp_type: &str, known_abstract: &std::collections::HashSet<String>) -> bool {
    known_abstract.iter().any(|name| {
        // Match whole-word occurrences to avoid false positives (e.g. "SubShape" matching "Shape")
        let ty = cpp_type;
        let mut start = 0;
        while let Some(pos) = ty[start..].find(name.as_str()) {
            let abs_start = start + pos;
            let abs_end = abs_start + name.len();
            let before_ok = abs_start == 0 || !ty.as_bytes()[abs_start - 1].is_ascii_alphanumeric();
            let after_ok = abs_end == ty.len() || !ty.as_bytes()[abs_end].is_ascii_alphanumeric();
            if before_ok && after_ok {
                return true;
            }
            start = abs_start + 1;
        }
        false
    })
}

fn has_abstract_types(return_type: &str, params: &[crate::ast::ParameterDecl], known_abstract: &std::collections::HashSet<String>) -> bool {
    references_abstract_class(return_type, known_abstract)
        || params.iter().any(|p| references_abstract_class(&p.qual_type, known_abstract))
}

fn render_rust_params(params: &[ParameterDecl]) -> String {
    params
        .iter()
        .enumerate()
        .map(|(index, param)| format!("arg{index}: {}", map_cpp_type(&param.qual_type, TypePosition::Param)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn cpp_param_list(params: &[ParameterDecl]) -> String {
    params
        .iter()
        .map(|param| param.qual_type.clone())
        .collect::<Vec<_>>()
        .join(", ")
}

fn rust_method_name(name: &str) -> String {
    rust_ident(&name.replace("operator", "operator_"))
}

fn rust_type_name(name: &str) -> String {
    simple_cpp_name(name).replace(':', "_")
}

fn rust_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    match out.as_str() {
        "fn" | "struct" | "type" | "mod" | "move" | "self" | "crate" => format!("r#{out}"),
        _ => out,
    }
}

fn simple_cpp_name(name: &str) -> String {
    name.split("::").last().unwrap_or(name).trim().to_string()
}

fn unique_name(used_names: &mut HashMap<String, usize>, base: &str) -> String {
    let entry = used_names.entry(base.to_string()).or_insert(0);
    if *entry == 0 {
        *entry = 1;
        base.to_string()
    } else {
        let value = *entry;
        *entry += 1;
        format!("{base}_{value}")
    }
}

fn operator_helper_name(class_name: &str, method_name: &str) -> String {
    format!("{}_{}", rust_ident(class_name), rust_ident(method_name))
}

/// Returns ` -> T` for non-void Rust return types, or empty string for `()`.
fn rust_ret_suffix(rust_type: &str) -> String {
    if rust_type == "()" {
        String::new()
    } else {
        format!(" -> {rust_type}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ClassDecl, MethodDecl, TranslationUnit};

    fn test_dir(name: &str) -> std::path::PathBuf {
        let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target/test-work/codegen")
            .join(format!("{name}-{}", std::process::id()));
        if root.exists() {
            std::fs::remove_dir_all(&root).unwrap();
        }
        std::fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn maps_basic_cpp_types() {
        assert_eq!(map_cpp_type("int", TypePosition::Param), "i32");
        assert_eq!(map_cpp_type("const char*", TypePosition::Param), "*const u8");
        assert_eq!(map_cpp_type("std::unique_ptr<Foo>", TypePosition::Return), "Foo");
    }

    #[test]
    fn void_return_omits_arrow() {
        assert_eq!(rust_ret_suffix("()"), "");
        assert_eq!(rust_ret_suffix("i32"), " -> i32");
    }

    #[test]
    fn renders_root_lib() {
        let lib = render_root_lib(&["alpha".into(), "beta".into()]);
        assert!(lib.contains("pub mod alpha;"));
        assert!(lib.contains("pub mod beta;"));
    }

    #[test]
    fn renders_class_with_interface() {
        let class = ClassDecl {
            name: "Shape".into(),
            qualified_name: "Shape".into(),
            is_abstract: true,
            methods: vec![MethodDecl {
                name: "area".into(),
                return_type: "double".into(),
                is_const: true,
                ..MethodDecl::default()
            }],
            ..ClassDecl::default()
        };
        let known_abstract: std::collections::HashSet<String> =
            std::iter::once("Shape".to_string()).collect();
        let abstract_methods: std::collections::HashMap<String, std::collections::HashSet<String>> =
            std::iter::once(("Shape".to_string(), std::iter::once("area".to_string()).collect())).collect();
        let rendered = render_class_decl(&class, &known_abstract, &abstract_methods);
        assert!(rendered.contains("#[interface]"));
        assert!(rendered.contains("fn area(&self) -> f64;"));
    }

    #[test]
    fn generates_feature_project_files() {
        let dir = test_dir("project");
        let layout = FeatureLayout::new(&dir, "demo");
        layout.ensure_dirs().unwrap();
        let source = dir.join("main.cpp");
        fs::write(&source, "int add(int a, int b) { return a + b; }").unwrap();
        let unit = TranslationUnit {
            source_path: source,
            module_name: "main".into(),
            functions: vec![FunctionDecl {
                name: "add".into(),
                qualified_name: "add".into(),
                return_type: "int".into(),
                params: vec![
                    ParameterDecl { name: "a".into(), qual_type: "int".into() },
                    ParameterDecl { name: "b".into(), qual_type: "int".into() },
                ],
                ..FunctionDecl::default()
            }],
            ..TranslationUnit::default()
        };
        generate_feature_project(&layout, &[unit]).unwrap();
        assert!(layout.rust_dir.join("Cargo.toml").exists());
        assert!(layout.rust_src_dir.join("main/mod.rs").exists());
        assert!(layout.rust_src_dir.join("lib.rs").exists());
    }
}
