use crate::error::Result;
use anyhow::anyhow;
use std::path::{Path, PathBuf};

// ─────────────────────────────────────────────
//  报告数据结构
// ─────────────────────────────────────────────

/// init 阶段单个编译单元的统计信息。
pub struct InitUnitStat {
    /// `.cpp2rust` 文件路径（用于显示）
    pub cpp2rust_path: String,
    /// 派生的 Rust 模块路径（如 `utils/foo`）
    pub unit_path: String,
    /// 解析到的 C++ 类数量
    pub class_count: usize,
    /// 解析到的 C++ 函数数量
    pub fn_count: usize,
    /// 解析到的 C++ 枚举数量
    pub enum_count: usize,
    /// 处理该文件耗时（毫秒）
    pub elapsed_ms: u128,
}

/// init 阶段报告所需的完整数据。
pub struct InitReportData<'a> {
    pub feature: &'a str,
    pub build_cmd: &'a str,
    pub captured_count: usize,
    pub selected_count: usize,
    pub units: &'a [InitUnitStat],
    /// 降级标签列表：`(tag, count)`，按 tag 名排序
    pub degraded_tags: &'a [(String, usize)],
}

/// merge 阶段报告所需的完整数据。
pub struct MergeReportData<'a> {
    pub feature: &'a str,
    pub unit_count: usize,
    /// 合并时发现的冲突描述列表
    pub conflicts: &'a [String],
}

/// Locate the project root by searching for `.cpp2rust/` upward from `start`.
/// Falls back to `start` itself if not found.
pub fn find_project_root(start: &Path) -> PathBuf {
    let mut cur = start.to_path_buf();
    loop {
        if cur.join(".cpp2rust").is_dir() {
            return cur;
        }
        match cur.parent() {
            Some(p) => cur = p.to_path_buf(),
            None => return start.to_path_buf(),
        }
    }
}

/// Layout of a single feature directory under `.cpp2rust/<feature>/`.
pub struct FeatureLayout {
    #[allow(dead_code)]
    pub project_root: PathBuf,
    /// `.cpp2rust/<feature>/`
    pub feature_root: PathBuf,
    /// `.cpp2rust/<feature>/c/`
    pub c_dir: PathBuf,
    /// `.cpp2rust/<feature>/rust/`
    pub rust_dir: PathBuf,
    /// `.cpp2rust/<feature>/meta/`
    pub meta_dir: PathBuf,
}

impl FeatureLayout {
    pub fn new(project_root: PathBuf, feature_name: &str) -> Self {
        let feature_root = project_root.join(".cpp2rust").join(feature_name);
        Self {
            c_dir: feature_root.join("c"),
            rust_dir: feature_root.join("rust"),
            meta_dir: feature_root.join("meta"),
            feature_root,
            project_root,
        }
    }

    /// Create all required directories.
    pub fn create_dirs(&self) -> Result<()> {
        for dir in [&self.c_dir, &self.rust_dir, &self.meta_dir] {
            std::fs::create_dir_all(dir)
                .map_err(|e| anyhow!("create dir {}: {}", dir.display(), e))?;
        }
        Ok(())
    }

    /// Write `meta/build_cmd.txt`.
    pub fn save_build_cmd(&self, cmd: &[String]) -> Result<()> {
        let path = self.meta_dir.join("build_cmd.txt");
        std::fs::write(&path, cmd.join(" ")).map_err(|e| anyhow!("write {}: {}", path.display(), e))
    }

    /// Write `meta/selected_files.json`.
    pub fn save_selected_files(&self, files: &[PathBuf]) -> Result<()> {
        let list: Vec<String> = files.iter().map(|p| p.display().to_string()).collect();
        let json = serde_json::to_string_pretty(&list)
            .map_err(|e| anyhow!("serialize selected_files: {}", e))?;
        let path = self.meta_dir.join("selected_files.json");
        std::fs::write(&path, json).map_err(|e| anyhow!("write {}: {}", path.display(), e))
    }

    /// Write `meta/init-report.md` with a summary of the init phase.
    pub fn save_init_report(&self, data: &InitReportData<'_>) -> Result<()> {
        let mut out = String::new();

        out.push_str(&format!("# Init Report — feature `{}`\n\n", data.feature));
        out.push_str(
            "Generated by **cpp2rust-demo init**.\n\n\
             Each row in the table below corresponds to a selected C++ compilation unit.\n\n---\n\n",
        );

        // 基本信息
        out.push_str("## Configuration\n\n");
        out.push_str(&format!("- **Build command:** `{}`\n", data.build_cmd));
        out.push_str(&format!(
            "- **Captured `.cpp2rust` files:** {}\n",
            data.captured_count
        ));
        out.push_str(&format!(
            "- **Selected files:** {}\n\n",
            data.selected_count
        ));
        out.push_str("---\n\n");

        // 编译单元统计表
        out.push_str("## Generated Units\n\n");
        if data.units.is_empty() {
            out.push_str("*(no units generated)*\n");
        } else {
            out.push_str(
                "| Source file | Rust module | Classes | Functions | Enums | Time (ms) |\n",
            );
            out.push_str(
                "|-------------|-------------|---------|-----------|-------|-----------|\n",
            );
            for u in data.units {
                out.push_str(&format!(
                    "| `{}` | `{}` | {} | {} | {} | {} |\n",
                    u.cpp2rust_path,
                    u.unit_path,
                    u.class_count,
                    u.fn_count,
                    u.enum_count,
                    u.elapsed_ms,
                ));
            }
        }
        out.push_str("\n---\n\n");

        // 降级特性
        out.push_str("## Degraded Features\n\n");
        if data.degraded_tags.is_empty() {
            out.push_str("*(none — all features mapped cleanly)*\n");
        } else {
            out.push_str(
                "The following feature tags require manual attention \
                 (search for `cpp2rust-todo` in the generated files):\n\n",
            );
            out.push_str("| Tag | Occurrences |\n|-----|-------------|\n");
            for (tag, count) in data.degraded_tags {
                out.push_str(&format!("| `{}` | {} |\n", tag, count));
            }
        }
        out.push_str("\n---\n\n");

        // 输出目录结构
        out.push_str("## Output Structure\n\n");
        out.push_str("```\n");
        out.push_str(&format!(".cpp2rust/{}/\n", data.feature));
        out.push_str("    ├── c/          (captured .cpp2rust files)\n");
        out.push_str("    ├── meta/       (build_cmd.txt, selected_files.json, init-report.md)\n");
        out.push_str(
            "    └── rust/       (generated Rust project: Cargo.toml, src/lib.rs, src/**/*.rs)\n",
        );
        out.push_str("```\n");

        let path = self.meta_dir.join("init-report.md");
        std::fs::write(&path, out).map_err(|e| anyhow!("write {}: {}", path.display(), e))
    }

    /// Write `meta/merge-report.md` with a summary of the merge phase.
    pub fn save_merge_report(&self, data: &MergeReportData<'_>) -> Result<()> {
        let mut out = String::new();

        out.push_str(&format!("# Merge Report — feature `{}`\n\n", data.feature));
        out.push_str(
            "Generated by **cpp2rust-demo merge**.\n\n\
             This document summarises the result of merging per-unit init output \
             into the final directory structure.\n\n---\n\n",
        );

        // 汇总
        out.push_str("## Summary\n\n");
        out.push_str(&format!("- **Unit files merged:** {}\n\n", data.unit_count));

        // 冲突
        out.push_str("## Conflicts\n\n");
        if data.conflicts.is_empty() {
            out.push_str("*(none)*\n");
        } else {
            for conflict in data.conflicts {
                out.push_str(&format!("- {}\n", conflict));
            }
        }
        out.push_str("\n---\n\n");

        // 输出目录结构
        out.push_str("## Output Structure\n\n");
        out.push_str("```\n");
        out.push_str(&format!(".cpp2rust/{}/rust/\n", data.feature));
        out.push_str("    ├── src.1/  (init 输出备份)\n");
        out.push_str("    ├── src.2/  (merge 输出，目录结构与 C++ 项目一致)\n");
        out.push_str("    └── src     (symlink → src.2)\n");
        out.push_str("```\n");

        let path = self.meta_dir.join("merge-report.md");
        std::fs::write(&path, out).map_err(|e| anyhow!("write {}: {}", path.display(), e))
    }
}

/// Scan `.cpp2rust/<feature>/c/` for all `*.cpp2rust` files.
pub fn scan_cpp2rust_files(c_dir: &Path) -> Result<Vec<PathBuf>> {
    if !c_dir.exists() {
        return Ok(vec![]);
    }
    let mut out = Vec::new();
    visit_dir(c_dir, &mut out)?;
    out.sort();
    Ok(out)
}

fn visit_dir(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in std::fs::read_dir(dir).map_err(|e| anyhow!("read_dir {}: {}", dir.display(), e))? {
        let entry = entry.map_err(|e| anyhow!("read entry: {}", e))?;
        let path = entry.path();
        if path.is_dir() {
            visit_dir(&path, out)?;
        } else if path.extension().is_some_and(|e| e == "cpp2rust") {
            out.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn find_project_root_in_current_dir() {
        let tmp = TempDir::new().unwrap();
        std::fs::create_dir(tmp.path().join(".cpp2rust")).unwrap();
        assert_eq!(find_project_root(tmp.path()), tmp.path());
    }

    #[test]
    fn find_project_root_in_parent() {
        let tmp = TempDir::new().unwrap();
        std::fs::create_dir(tmp.path().join(".cpp2rust")).unwrap();
        let sub = tmp.path().join("sub");
        std::fs::create_dir(&sub).unwrap();
        assert_eq!(find_project_root(&sub), tmp.path());
    }

    #[test]
    fn find_project_root_fallback() {
        let tmp = TempDir::new().unwrap();
        let sub = tmp.path().join("sub");
        std::fs::create_dir(&sub).unwrap();
        assert_eq!(find_project_root(&sub), sub);
    }

    #[test]
    fn feature_layout_create_dirs() {
        let tmp = TempDir::new().unwrap();
        let layout = FeatureLayout::new(tmp.path().to_path_buf(), "default");
        layout.create_dirs().unwrap();
        assert!(layout.c_dir.exists());
        assert!(layout.rust_dir.exists());
        assert!(layout.meta_dir.exists());
    }

    #[test]
    fn save_build_cmd_writes_file() {
        let tmp = TempDir::new().unwrap();
        let layout = FeatureLayout::new(tmp.path().to_path_buf(), "default");
        layout.create_dirs().unwrap();
        layout
            .save_build_cmd(&["make".into(), "-j4".into()])
            .unwrap();
        let content = std::fs::read_to_string(layout.meta_dir.join("build_cmd.txt")).unwrap();
        assert_eq!(content, "make -j4");
    }

    #[test]
    fn save_selected_files_writes_json() {
        let tmp = TempDir::new().unwrap();
        let layout = FeatureLayout::new(tmp.path().to_path_buf(), "default");
        layout.create_dirs().unwrap();
        let files = vec![PathBuf::from("/foo/bar.cpp2rust")];
        layout.save_selected_files(&files).unwrap();
        let content = std::fs::read_to_string(layout.meta_dir.join("selected_files.json")).unwrap();
        assert!(content.contains("bar.cpp2rust"));
    }

    #[test]
    fn scan_cpp2rust_files_empty_dir() {
        let tmp = TempDir::new().unwrap();
        let files = scan_cpp2rust_files(tmp.path()).unwrap();
        assert!(files.is_empty());
    }

    #[test]
    fn scan_cpp2rust_files_finds_files() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("a.cpp2rust"), "").unwrap();
        std::fs::write(tmp.path().join("b.cpp"), "").unwrap();
        let files = scan_cpp2rust_files(tmp.path()).unwrap();
        assert_eq!(files.len(), 1);
        assert!(files[0].ends_with("a.cpp2rust"));
    }

    #[test]
    fn save_init_report_creates_file() {
        let tmp = TempDir::new().unwrap();
        let layout = FeatureLayout::new(tmp.path().to_path_buf(), "myfeature");
        layout.create_dirs().unwrap();

        let units = vec![InitUnitStat {
            cpp2rust_path: "c/src/foo.cpp.cpp2rust".into(),
            unit_path: "foo".into(),
            class_count: 2,
            fn_count: 3,
            enum_count: 1,
            elapsed_ms: 42,
        }];
        let tags = vec![("cpp_default".into(), 1usize)];
        let data = InitReportData {
            feature: "myfeature",
            build_cmd: "make -j4",
            captured_count: 5,
            selected_count: 1,
            units: &units,
            degraded_tags: &tags,
        };
        layout.save_init_report(&data).unwrap();

        let content = std::fs::read_to_string(layout.meta_dir.join("init-report.md")).unwrap();
        assert!(content.contains("# Init Report — feature `myfeature`"));
        assert!(content.contains("make -j4"));
        assert!(content.contains("foo"));
        assert!(content.contains("cpp_default"));
        assert!(content.contains("2")); // class_count
    }

    #[test]
    fn save_merge_report_creates_file() {
        let tmp = TempDir::new().unwrap();
        let layout = FeatureLayout::new(tmp.path().to_path_buf(), "default");
        layout.create_dirs().unwrap();

        let data = MergeReportData {
            feature: "default",
            unit_count: 7,
            conflicts: &[],
        };
        layout.save_merge_report(&data).unwrap();

        let content = std::fs::read_to_string(layout.meta_dir.join("merge-report.md")).unwrap();
        assert!(content.contains("# Merge Report — feature `default`"));
        assert!(content.contains("7"));
        assert!(content.contains("*(none)*"));
    }

    #[test]
    fn save_merge_report_lists_conflicts() {
        let tmp = TempDir::new().unwrap();
        let layout = FeatureLayout::new(tmp.path().to_path_buf(), "default");
        layout.create_dirs().unwrap();

        let conflicts = vec!["conflict A".into(), "conflict B".into()];
        let data = MergeReportData {
            feature: "default",
            unit_count: 2,
            conflicts: &conflicts,
        };
        layout.save_merge_report(&data).unwrap();

        let content = std::fs::read_to_string(layout.meta_dir.join("merge-report.md")).unwrap();
        assert!(content.contains("conflict A"));
        assert!(content.contains("conflict B"));
    }
}
