use crate::error::Result;
use crate::layout::FeatureLayout;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Default)]
pub struct MergeSummary {
    pub modules: Vec<String>,
    pub shared_forward_decls: Vec<String>,
    pub shared_type_aliases: Vec<String>,
}

pub fn merge_feature(layout: &FeatureLayout) -> Result<MergeSummary> {
    let source_dir = current_source_dir(layout)?;
    let dest_dir = layout.rust_dir.join("src.2");
    if dest_dir.exists() {
        remove_path(&dest_dir)?;
    }
    fs::create_dir_all(&dest_dir)?;

    let mut summary = summarize_source_tree(&source_dir)?;
    for module in &summary.modules {
        copy_tree(&source_dir.join(module), &dest_dir.join(module))?;
    }
    let lib_rs = source_dir.join("lib.rs");
    let base_lib = if lib_rs.exists() {
        fs::read_to_string(&lib_rs)?
    } else {
        String::from("// generated by cpp2rust-demo\n")
    };
    fs::write(dest_dir.join("lib.rs"), render_merged_lib(&base_lib, &summary))?;

    let backup_dir = layout.rust_dir.join("src.1");
    if backup_dir.exists() {
        remove_path(&backup_dir)?;
    }
    if layout.rust_src_dir.exists() && !symlink_metadata_is_symlink(&layout.rust_src_dir)? {
        fs::rename(&layout.rust_src_dir, &backup_dir)?;
    } else if layout.rust_src_dir.exists() {
        fs::remove_file(&layout.rust_src_dir)?;
    }
    #[cfg(unix)]
    std::os::unix::fs::symlink("src.2", &layout.rust_src_dir)?;

    let mut report = String::from("# merge interface report\n\n");
    report.push_str(&format!("- modules: {}\n", summary.modules.join(", ")));
    report.push_str(&format!("- shared forward declarations: {}\n", summary.shared_forward_decls.join(", ")));
    report.push_str(&format!("- shared type aliases: {}\n", summary.shared_type_aliases.join(", ")));
    fs::write(layout.merge_report_path(), report)?;

    summary.modules.sort();
    Ok(summary)
}

fn current_source_dir(layout: &FeatureLayout) -> Result<PathBuf> {
    if layout.rust_src_dir.exists() && symlink_metadata_is_symlink(&layout.rust_src_dir)? {
        let target = fs::read_link(&layout.rust_src_dir)?;
        Ok(layout.rust_dir.join(target))
    } else {
        Ok(layout.rust_src_dir.clone())
    }
}

fn summarize_source_tree(source_dir: &Path) -> Result<MergeSummary> {
    let mut modules = Vec::new();
    let mut forward_counts = BTreeMap::<String, usize>::new();
    let mut alias_counts = BTreeMap::<String, usize>::new();
    if !source_dir.exists() {
        return Ok(MergeSummary::default());
    }
    for entry in fs::read_dir(source_dir)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            let module_name = entry.file_name().to_string_lossy().to_string();
            modules.push(module_name);
            let mod_rs = path.join("mod.rs");
            if mod_rs.exists() {
                tally_lines(&mod_rs, &mut forward_counts, |line| line.starts_with("class "))?;
            }
            let types_rs = path.join("types.rs");
            if types_rs.exists() {
                tally_lines(&types_rs, &mut alias_counts, |line| line.starts_with("pub type "))?;
            }
        }
    }
    modules.sort();
    Ok(MergeSummary {
        modules,
        shared_forward_decls: forward_counts
            .into_iter()
            .filter_map(|(line, count)| (count > 1).then_some(line))
            .collect(),
        shared_type_aliases: alias_counts
            .into_iter()
            .filter_map(|(line, count)| (count > 1).then_some(line))
            .collect(),
    })
}

fn tally_lines<F>(path: &Path, counts: &mut BTreeMap<String, usize>, predicate: F) -> Result<()>
where
    F: Fn(&str) -> bool,
{
    let content = fs::read_to_string(path)?;
    for line in content.lines().map(str::trim).filter(|line| predicate(line)) {
        *counts.entry(line.to_string()).or_default() += 1;
    }
    Ok(())
}

fn render_merged_lib(base_lib: &str, summary: &MergeSummary) -> String {
    let mut out = String::new();
    out.push_str(base_lib);
    if !base_lib.ends_with('\n') {
        out.push('\n');
    }
    if !summary.shared_forward_decls.is_empty() || !summary.shared_type_aliases.is_empty() {
        out.push_str("\n// merged shared declarations\n");
    }
    for line in &summary.shared_forward_decls {
        out.push_str(&format!("// {line}\n"));
    }
    for line in &summary.shared_type_aliases {
        out.push_str(&format!("// {line}\n"));
    }
    out
}

fn copy_tree(from: &Path, to: &Path) -> Result<()> {
    fs::create_dir_all(to)?;
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let src = entry.path();
        let dst = to.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_tree(&src, &dst)?;
        } else {
            fs::copy(&src, &dst)?;
        }
    }
    Ok(())
}

fn remove_path(path: &Path) -> Result<()> {
    if symlink_metadata_is_symlink(path)? {
        fs::remove_file(path)?;
    } else if path.is_dir() {
        fs::remove_dir_all(path)?;
    } else if path.exists() {
        fs::remove_file(path)?;
    }
    Ok(())
}

fn symlink_metadata_is_symlink(path: &Path) -> Result<bool> {
    Ok(fs::symlink_metadata(path)?.file_type().is_symlink())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_dir(name: &str) -> PathBuf {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target/test-work/merge")
            .join(format!("{name}-{}", std::process::id()));
        if root.exists() {
            std::fs::remove_dir_all(&root).unwrap();
        }
        std::fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn summarizes_duplicate_declarations() {
        let dir = test_dir("summary");
        let src = dir.join("src");
        fs::create_dir_all(src.join("a")).unwrap();
        fs::create_dir_all(src.join("b")).unwrap();
        fs::write(src.join("a/mod.rs"), "class Foo;\n").unwrap();
        fs::write(src.join("b/mod.rs"), "class Foo;\n").unwrap();
        fs::write(src.join("a/types.rs"), "pub type Num = i32;\n").unwrap();
        fs::write(src.join("b/types.rs"), "pub type Num = i32;\n").unwrap();
        let summary = summarize_source_tree(&src).unwrap();
        assert_eq!(summary.shared_forward_decls, vec!["class Foo;"]);
        assert_eq!(summary.shared_type_aliases, vec!["pub type Num = i32;"]);
    }

    #[test]
    fn renders_merged_lib_with_comments() {
        let rendered = render_merged_lib("pub mod a;\n", &MergeSummary {
            shared_forward_decls: vec!["class Foo;".into()],
            ..MergeSummary::default()
        });
        assert!(rendered.contains("// class Foo;"));
    }

    #[test]
    fn merges_feature_structure() {
        let dir = test_dir("feature");
        let layout = FeatureLayout::new(&dir, "demo");
        layout.ensure_dirs().unwrap();
        fs::create_dir_all(layout.rust_src_dir.join("main")).unwrap();
        fs::write(layout.rust_src_dir.join("lib.rs"), "pub mod main;\n").unwrap();
        fs::write(layout.rust_src_dir.join("main/mod.rs"), "class Foo;\n").unwrap();
        fs::write(layout.rust_src_dir.join("main/types.rs"), "pub type Num = i32;\n").unwrap();
        let summary = merge_feature(&layout).unwrap();
        assert_eq!(summary.modules, vec!["main".to_string()]);
        assert!(layout.rust_dir.join("src.1").exists());
        assert!(layout.rust_dir.join("src.2/lib.rs").exists());
    }
}
