//! `merge` command implementation.
//!
//! The `merge` command reads all per-header `ffi_*.rs` files produced by
//! `init` and combines them into a single `merged_ffi.rs`.  It:
//!
//! 1. Concatenates the `import_class!` blocks from all files.
//! 2. Merges all `import_lib!` blocks into one, de-duplicating `class` forward
//!    declarations and consolidating all `#[cpp(func = ...)]` items under a
//!    single `#![link_name = "..."]` attribute.
//! 3. Writes `merged_ffi.rs` to `.cpp2rust/<feature>/rust/src/`.
//! 4. Writes a Markdown interface-checklist to `.cpp2rust/<feature>/meta/`.

use crate::error::Result;
use anyhow::anyhow;
use std::fs;
use std::path::{Path, PathBuf};

/// Merge all `ffi_*.rs` files inside `rust_src_dir` into a single
/// `merged_ffi.rs` written to the same directory.
///
/// Returns the path to the merged file.
pub fn merge_ffi_files(rust_src_dir: &Path, link_name: &str) -> Result<PathBuf> {
    // Collect all ffi_*.rs files, sorted for determinism.
    let mut ffi_files: Vec<PathBuf> = fs::read_dir(rust_src_dir)
        .map_err(|e| anyhow!("read dir {}: {}", rust_src_dir.display(), e))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with("ffi_") && n.ends_with(".rs"))
                .unwrap_or(false)
        })
        .collect();
    ffi_files.sort();

    if ffi_files.is_empty() {
        return Err(anyhow!(
            "no ffi_*.rs files found in {}; run 'init' first",
            rust_src_dir.display()
        ));
    }

    println!(
        "Merging {} ffi file(s) in {}",
        ffi_files.len(),
        rust_src_dir.display()
    );

    let mut cpp_includes: indexmap::IndexSet<String> = Default::default();
    let mut import_class_blocks: Vec<String> = Vec::new();
    let mut forward_decls: indexmap::IndexSet<String> = Default::default();
    let mut fn_items: Vec<String> = Vec::new();
    let mut headers_seen: Vec<String> = Vec::new();

    for path in &ffi_files {
        let src =
            fs::read_to_string(path).map_err(|e| anyhow!("read {}: {}", path.display(), e))?;

        // Extract the header comment.
        if let Some(header) = extract_comment_field(&src, "Source file")
            .or_else(|| extract_comment_field(&src, "Source header"))
        {
            headers_seen.push(header);
        }

        // Extract hicc::cpp! include blocks (deduplicated).
        for include in extract_cpp_includes(&src) {
            cpp_includes.insert(include);
        }

        // Extract import_class! blocks.
        for block in extract_import_class_blocks(&src) {
            import_class_blocks.push(block);
        }

        // Extract forward declarations and fn items from import_lib! blocks.
        for block in extract_import_lib_blocks(&src) {
            let (fwd, fns) = parse_lib_block_contents(&block);
            for f in fwd {
                forward_decls.insert(f);
            }
            fn_items.extend(fns);
        }
    }

    // Compose the merged file.
    let mut out = String::new();
    out.push_str("// Merged FFI – auto-generated by `cpp2rust-demo merge`.\n");
    out.push_str("// Source files:\n");
    for h in &headers_seen {
        out.push_str(&format!("//   {}\n", h));
    }
    out.push('\n');
    out.push_str("#![allow(non_snake_case, dead_code)]\n\n");

    // Consolidated hicc::cpp! block with all unique includes.
    if !cpp_includes.is_empty() {
        out.push_str("hicc::cpp! {\n");
        for include in cpp_includes.iter() {
            out.push_str(&format!("    {}\n", include));
        }
        out.push_str("}\n\n");
    }

    for block in &import_class_blocks {
        out.push_str(block.trim());
        out.push_str("\n\n");
    }

    out.push_str("hicc::import_lib! {\n");
    out.push_str(&format!("    #![link_name = \"{}\"]\n\n", link_name));
    for fwd in forward_decls.iter() {
        out.push_str(&format!("    {}\n", fwd));
    }
    if !forward_decls.is_empty() && !fn_items.is_empty() {
        out.push('\n');
    }
    for item in &fn_items {
        for line in item.lines() {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str("}\n");

    let merged_path = rust_src_dir.join("merged_ffi.rs");
    fs::write(&merged_path, &out).map_err(|e| anyhow!("write {}: {}", merged_path.display(), e))?;

    println!("  → {}", merged_path.display());
    Ok(merged_path)
}

// ---------------------------------------------------------------------------
// Simple text extraction helpers
// ---------------------------------------------------------------------------

/// Extract the value of a `// Key : value` comment header.
fn extract_comment_field(src: &str, field: &str) -> Option<String> {
    for line in src.lines() {
        if let Some(rest) = line.strip_prefix("// ") {
            if let Some(val) = rest.strip_prefix(field) {
                if let Some(val) = val.strip_prefix(" : ") {
                    return Some(val.trim().to_string());
                }
            }
        }
    }
    None
}

/// Extract `hicc::import_class! { ... }` blocks from `src`.
fn extract_import_class_blocks(src: &str) -> Vec<String> {
    extract_macro_blocks(src, "hicc::import_class!")
}

/// Extract `hicc::import_lib! { ... }` blocks from `src`.
fn extract_import_lib_blocks(src: &str) -> Vec<String> {
    extract_macro_blocks(src, "hicc::import_lib!")
}

/// Extract individual `#include "..."` lines from all `hicc::cpp! { ... }` blocks.
///
/// Returns a list of well-formed include directives (e.g. `#include "mylib.hpp"`
/// or `#include <header>`) in the order they appear.  Lines that start with
/// `#include` but do not match either quoting style are silently skipped.
/// The caller is responsible for de-duplication.
fn extract_cpp_includes(src: &str) -> Vec<String> {
    let mut includes = Vec::new();
    for block in extract_macro_blocks(src, "hicc::cpp!") {
        let inner = strip_block_wrapper(&block);
        for line in inner.lines() {
            let trimmed = line.trim();
            // Accept only well-formed: #include "..." or #include <...>
            if is_valid_include(trimmed) {
                includes.push(trimmed.to_string());
            }
        }
    }
    includes
}

/// Return true if `line` is a well-formed `#include` directive.
///
/// Accepts:
/// - `#include "something.hpp"` (user headers)
/// - `#include <something>` (system headers)
fn is_valid_include(line: &str) -> bool {
    if !line.starts_with("#include") {
        return false;
    }
    let rest = line["#include".len()..].trim();
    (rest.starts_with('"') && rest.ends_with('"') && rest.len() >= 2)
        || (rest.starts_with('<') && rest.ends_with('>') && rest.len() >= 2)
}

/// Generic block extractor: finds all occurrences of `macro_prefix { ... }`
/// using brace-depth counting.
fn extract_macro_blocks(src: &str, macro_prefix: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut search_from = 0;

    while let Some(start) = src[search_from..].find(macro_prefix) {
        let abs_start = search_from + start;
        let brace_start = match src[abs_start..].find('{') {
            Some(b) => abs_start + b,
            None => break,
        };

        let mut depth = 0usize;
        let mut end = brace_start;
        for (i, ch) in src[brace_start..].char_indices() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = brace_start + i + 1;
                        break;
                    }
                }
                _ => {}
            }
        }

        blocks.push(src[abs_start..end].to_string());
        search_from = end;
    }

    blocks
}

/// Parse the inner contents of an `import_lib! { ... }` block into
/// (forward_declarations, fn_items).
fn parse_lib_block_contents(block: &str) -> (Vec<String>, Vec<String>) {
    // Strip the outer `hicc::import_lib! {` ... `}` wrapper.
    let inner = strip_block_wrapper(block);

    let mut forward_decls = Vec::new();
    let mut fn_items = Vec::new();
    let mut current_item = String::new();
    let mut in_item = false;

    for line in inner.lines() {
        let trimmed = line.trim();

        // Skip link_name attribute.
        if trimmed.starts_with("#![link_name") {
            continue;
        }

        // Forward declaration: `class Foo;`
        if trimmed.starts_with("class ") && trimmed.ends_with(';') && !trimmed.contains("//") {
            forward_decls.push(trimmed.to_string());
            continue;
        }

        // Skip blank lines between items when not inside an item.
        if trimmed.is_empty() && !in_item {
            continue;
        }

        // Accumulate fn items (they may span multiple lines: attribute + fn).
        if trimmed.starts_with("#[cpp(func") || (in_item && !trimmed.is_empty()) {
            in_item = true;
            if !current_item.is_empty() {
                current_item.push('\n');
            }
            current_item.push_str(trimmed);

            // A fn item ends with `;`.
            if trimmed.ends_with(';') {
                fn_items.push(current_item.trim().to_string());
                current_item.clear();
                in_item = false;
            }
        }
    }

    (forward_decls, fn_items)
}

/// Strip the outer macro wrapper from a block string, returning just the inner
/// content (the part between the outermost `{` and `}`).
fn strip_block_wrapper(block: &str) -> &str {
    let open = block.find('{').unwrap_or(0);
    let close = block.rfind('}').unwrap_or(block.len());
    &block[open + 1..close]
}

// ---------------------------------------------------------------------------
// indexmap shim (we avoid adding indexmap as a real dep; use Vec for ordering)
// ---------------------------------------------------------------------------

// Actually, use a simple ordered-set based on Vec to avoid the extra dep.
mod indexmap {
    #[derive(Default)]
    pub struct IndexSet<T> {
        items: Vec<T>,
    }

    impl<T: Eq + Clone> IndexSet<T> {
        pub fn insert(&mut self, value: T) -> bool {
            if !self.items.contains(&value) {
                self.items.push(value);
                true
            } else {
                false
            }
        }

        pub fn iter(&self) -> impl Iterator<Item = &T> {
            self.items.iter()
        }

        pub fn is_empty(&self) -> bool {
            self.items.is_empty()
        }
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_import_class_block() {
        let src = r#"
hicc::import_class! {
    #[cpp(class = "Widget")]
    class Widget {
        #[cpp(method = "void update(double, double)")]
        fn update(&mut self, x: f64, y: f64);
    }
}
"#;
        let blocks = extract_import_class_blocks(src);
        assert_eq!(blocks.len(), 1);
        assert!(blocks[0].contains("Widget"));
    }

    #[test]
    fn extract_import_lib_block() {
        let src = r#"
hicc::import_lib! {
    #![link_name = "mylib"]

    class Widget;

    #[cpp(func = "int add(int, int)")]
    fn add(a: i32, b: i32) -> i32;
}
"#;
        let blocks = extract_import_lib_blocks(src);
        assert_eq!(blocks.len(), 1);

        let (fwd, fns) = parse_lib_block_contents(&blocks[0]);
        assert_eq!(fwd, vec!["class Widget;"]);
        assert_eq!(fns.len(), 1);
        assert!(fns[0].contains("fn add"));
    }

    #[test]
    fn extract_comment_field_works() {
        let src = "// Source file : mylib.cpp2rust\n// Link library   : mylib\n";
        assert_eq!(
            extract_comment_field(src, "Source file"),
            Some("mylib.cpp2rust".to_string())
        );
    }

    #[test]
    fn merge_deduplicates_forward_decls() {
        let src1 = r#"
hicc::import_lib! {
    #![link_name = "mylib"]

    class Widget;

    #[cpp(func = "int foo()")]
    fn foo() -> i32;
}
"#;
        let src2 = r#"
hicc::import_lib! {
    #![link_name = "mylib"]

    class Widget;

    #[cpp(func = "int bar()")]
    fn bar() -> i32;
}
"#;
        // Simulate merging two blocks.
        let mut fwd: indexmap::IndexSet<String> = Default::default();
        let mut fns: Vec<String> = Vec::new();
        for block in extract_import_lib_blocks(src1)
            .iter()
            .chain(extract_import_lib_blocks(src2).iter())
        {
            let (f, i) = parse_lib_block_contents(block);
            for fd in f {
                fwd.insert(fd);
            }
            fns.extend(i);
        }
        let fwd_vec: Vec<&String> = fwd.iter().collect();
        assert_eq!(fwd_vec.len(), 1, "Widget should appear only once");
        assert_eq!(fns.len(), 2);
    }
}
